/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admins": {
        /**
         * List school admins with pagination and filters (invited/accepted)
         * Delete school members by user IDs; returns error if current user is included
         */
        get: {
            parameters: {
                query: {
                    /** Page number (default 1) */
                    page?: number;
                    /** Page size (default 50) */
                    limit?: number;
                    /** Search email or full name */
                    search?: string;
                    /** Filter by invitation status: invited|accepted|all (default all) */
                    invitation_status?: string;
                };
                body: {
                    /** User IDs to delete */
                    body: definitions["api.deleteAdminsRequest"];
                };
            };
            responses: {
                /** OK */
                200: {
                    schema: { [key: string]: unknown };
                };
                /** Bad Request */
                400: {
                    schema: { [key: string]: unknown };
                };
                /** Unauthorized */
                401: {
                    schema: { [key: string]: unknown };
                };
            };
        };
        /**
         * List school admins with pagination and filters (invited/accepted)
         * Delete school members by user IDs; returns error if current user is included
         */
        delete: {
            parameters: {
                query: {
                    /** Page number (default 1) */
                    page?: number;
                    /** Page size (default 50) */
                    limit?: number;
                    /** Search email or full name */
                    search?: string;
                    /** Filter by invitation status: invited|accepted|all (default all) */
                    invitation_status?: string;
                };
                body: {
                    /** User IDs to delete */
                    body: definitions["api.deleteAdminsRequest"];
                };
            };
            responses: {
                /** OK */
                200: {
                    schema: { [key: string]: unknown };
                };
                /** Bad Request */
                400: {
                    schema: { [key: string]: unknown };
                };
                /** Unauthorized */
                401: {
                    schema: { [key: string]: unknown };
                };
            };
        };
    };
    "/api/auth/callback": {
        get: operations["_api_auth_callback"];
    };
    "/api/auth/invite/callback": {
        get: {
            parameters: {
                query: {
                    /** Invitation token */
                    token: string;
                };
            };
            responses: {
                /** Redirects to frontend */
                302: never;
            };
        };
    };
    "/api/auth/logout": {
        post: operations["_api_auth_logout"];
    };
    "/api/auth/magic-link/send": {
        post: operations["_api_auth_magic-link_send"];
    };
    "/api/me": {
        get: {
            responses: {
                /** OK */
                200: {
                    schema: { [key: string]: unknown };
                };
                /** Unauthorized */
                401: {
                    schema: { [key: string]: unknown };
                };
            };
        };
    };
    "/api/school": {
        /** Creates a new school. Requester must be admin. Auto-creates 3 terms + loads CBE curriculum. */
        post: {
            parameters: {
                body: {
                    /** School creation payload */
                    body: { [key: string]: unknown };
                };
            };
            responses: {
                /** Created */
                201: {
                    schema: { [key: string]: unknown };
                };
                /** Bad Request */
                400: {
                    schema: { [key: string]: unknown };
                };
                /** Forbidden */
                403: {
                    schema: { [key: string]: unknown };
                };
            };
        };
    };
    "/api/school/academic-period": {
        /** Creates a new academic year with nested terms for the active school. */
        post: {
            parameters: {
                body: {
                    /** Academic period payload */
                    body: definitions["services.AcademicPeriodRequest"];
                };
            };
            responses: {
                /** Created */
                201: {
                    schema: { [key: string]: unknown };
                };
                /** Bad Request */
                400: {
                    schema: { [key: string]: unknown };
                };
                /** Unauthorized */
                401: {
                    schema: { [key: string]: unknown };
                };
            };
        };
    };
    "/school/classes": {
        get: {
            parameters: {
                query: {
                    /** Page number */
                    page?: number;
                    /** Page size */
                    limit?: number;
                    /** Search by name */
                    search?: string;
                    /** Comma separated grade labels */
                    grade?: string;
                    /** Comma separated stream names */
                    stream?: string;
                };
            };
            responses: {
                /** OK */
                200: {
                    schema: { [key: string]: unknown };
                };
                /** Unauthorized */
                401: {
                    schema: { [key: string]: unknown };
                };
            };
        };
        post: {
            parameters: {
                body: {
                    /** Class payload */
                    body: definitions["api.createClassRequest"];
                };
            };
            responses: {
                /** Created */
                201: {
                    schema: { [key: string]: unknown };
                };
                /** Bad Request */
                400: {
                    schema: { [key: string]: unknown };
                };
                /** Unauthorized */
                401: {
                    schema: { [key: string]: unknown };
                };
            };
        };
    };
    "/school/classes/{id}": {
        get: {
            parameters: {
                path: {
                    /** Class ID */
                    id: string;
                };
            };
            responses: {
                /** OK */
                200: {
                    schema: { [key: string]: unknown };
                };
                /** Unauthorized */
                401: {
                    schema: { [key: string]: unknown };
                };
                /** Not Found */
                404: {
                    schema: { [key: string]: unknown };
                };
            };
        };
    };
    "/school/grades": {
        get: {
            responses: {
                /** OK */
                200: {
                    schema: { [key: string]: unknown }[];
                };
                /** Bad Request */
                400: {
                    schema: { [key: string]: unknown };
                };
                /** Unauthorized */
                401: {
                    schema: { [key: string]: unknown };
                };
            };
        };
    };
    "/school/register": {
        /** Creates a new school for the authenticated user and assigns them as ADMIN. Updates user's full_name atomically. */
        post: {
            parameters: {
                body: {
                    /** School registration payload */
                    body: { [key: string]: unknown };
                };
            };
            responses: {
                /** Created */
                201: {
                    schema: { [key: string]: unknown };
                };
                /** Bad Request */
                400: {
                    schema: { [key: string]: unknown };
                };
            };
        };
    };
    "/school/set-active": {
        /** Updates the user's active school in DB and session. */
        post: {
            parameters: {
                body: {
                    /** Active school payload */
                    body: { [key: string]: unknown };
                };
            };
            responses: {
                /** OK */
                200: {
                    schema: { [key: string]: unknown };
                };
                /** Bad Request */
                400: {
                    schema: { [key: string]: unknown };
                };
            };
        };
    };
    "/school/streams": {
        /** Creates one or more streams for the active school. */
        post: {
            parameters: {
                body: {
                    /** Stream names */
                    body: string[];
                };
            };
            responses: {
                /** Created */
                201: {
                    schema: { [key: string]: unknown };
                };
                /** Bad Request */
                400: {
                    schema: { [key: string]: unknown };
                };
                /** Unauthorized */
                401: {
                    schema: { [key: string]: unknown };
                };
            };
        };
    };
    "/api/admins/invitations": {
        post: operations["_api_admins_invitations"];
    };
    "/api/admins/invitations/jobs/{job_id}": {
        get: operations["_api_admins_invitations_jobs_j"];
    };
    "/api/admins/invitations/jobs/{job_id}/retry-failed": {
        post: operations["_api_admins_invitations_jobs_j"];
    };
}

export interface definitions {
    "api.createClassRequest": {
        gradeId?: string;
        name?: string;
        streamId?: string;
    };
    "api.deleteAdminsRequest": {
        user_ids?: string[];
    };
    "services.AcademicPeriodRequest": {
        terms?: definitions["services.TermInput"][];
        year?: number;
    };
    "services.AdminListItem": {
        accepted_at?: string;
        created_at?: string;
        email?: string;
        full_name?: string;
        invited_at?: string;
        is_active?: boolean;
        membership_id?: string;
        user_id?: string;
    };
    "services.AdminListResponse": {
        items?: definitions["services.AdminListItem"][];
        limit?: number;
        page?: number;
        total?: number;
    };
    "services.TermInput": {
        end_date?: string;
        name?: string;
        /** @description "2026-01-15" */
        start_date?: string;
    };
    "api.InvitationRow": {
        email: string;
        full_name: string;
    };
    "api.BulkInvitationRequest": {
        invitations: definitions["api.InvitationRow"][];
    };
    "api.BulkInvitationResponse": {
        job_id?: string;
        status?: string;
        total_records?: number;
        message?: string;
    };
    "api.InvitationJob": {
        job_id?: string;
        status?: string;
        total_records?: number;
    };
    "api.InvitationRetryResponse": {
        job_id?: string;
        status?: string;
        message?: string;
    };
    "api.MagicLinkRequest": {
        email: string;
        org_id?: string;
    };
    "api.MagicLinkResponse": {
        code?: string;
        message?: string;
        errors?: { [key: string]: unknown };
    };
    "api.CallbackResponse": {
        code?: string;
        message?: string;
        errors?: { [key: string]: unknown };
    };
    "api.LogoutResponse": {
        code?: string;
        message?: string;
        errors?: { [key: string]: unknown };
    };
}

export interface operations {
    _api_auth_callback: {
        parameters: {
            query: {
                token: string;
            };
        };
        responses: {
            /** OK */
            200: {
                schema: definitions["api.CallbackResponse"];
            };
        };
    };
    _api_auth_logout: {
        parameters: {};
        responses: {
            /** OK */
            200: {
                schema: definitions["api.LogoutResponse"];
            };
        };
    };
    "_api_auth_magic-link_send": {
        parameters: {
            formData: {
                email?: string;
            };
            body: {
                body?: definitions["api.MagicLinkRequest"];
            };
        };
        responses: {
            /** OK */
            200: {
                schema: definitions["api.MagicLinkResponse"];
            };
        };
    };
    _api_admins_invitations: {
        parameters: {
            body: {
                body: definitions["api.BulkInvitationRequest"];
            };
        };
        responses: {
            /** OK */
            200: {
                schema: definitions["api.BulkInvitationResponse"];
            };
            /** Accepted */
            202: {
                schema: definitions["api.BulkInvitationResponse"];
            };
        };
    };
    _api_admins_invitations_jobs_j: {
        parameters: {
            path: {
                job_id: string;
            };
        };
        responses: {
            /** OK */
            200: {
                schema: definitions["api.InvitationRetryResponse"];
            };
        };
    };
}

export interface external {}

// Named type re-exports for frontend compatibility
export type InvitationRow = definitions["api.InvitationRow"];
export type BulkInvitationRequest = definitions["api.BulkInvitationRequest"];
export type BulkInvitationResponse = definitions["api.BulkInvitationResponse"];
export type InvitationJob = definitions["api.InvitationJob"];
export type InvitationRetryResponse = definitions["api.InvitationRetryResponse"];
export type MagicLinkRequest = definitions["api.MagicLinkRequest"];
export type MagicLinkResponse = definitions["api.MagicLinkResponse"];
export type CallbackResponse = definitions["api.CallbackResponse"];
export type LogoutResponse = definitions["api.LogoutResponse"];

export interface CreateSchoolPayload {
    name: string;
    domain?: string;
}
export interface CreateSchoolResponse {
    id: string;
    name: string;
    domain?: string;
}
export interface ListSchoolsResponse {
    items: Array<{ id: string; name: string; domain?: string }>;
    total?: number;
}

export interface BulkInvitationResponseExtended extends BulkInvitationResponse {
    count?: number;
}
