/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/callback": {
        get: {
            parameters: {
                query: {
                    /** Magic-link token */
                    token: string;
                };
            };
            responses: {
                /** OK */
                200: {
                    schema: { [key: string]: unknown };
                };
            };
        };
    };
    "/api/auth/logout": {
        post: {
            responses: {
                /** OK */
                200: {
                    schema: { [key: string]: unknown };
                };
            };
        };
    };
    "/api/auth/magic-link/send": {
        post: {
            parameters: {
                formData: {
                    /** User email */
                    email: string;
                };
                query: {
                    /** Organization ID or slug */
                    org_id?: string;
                };
            };
            responses: {
                /** OK */
                200: {
                    schema: { [key: string]: unknown };
                };
            };
        };
    };
    "/api/me": {
        get: {
            responses: {
                /** OK */
                200: {
                    schema: { [key: string]: unknown };
                };
                /** Unauthorized */
                401: {
                    schema: { [key: string]: unknown };
                };
            };
        };
    };
    "/register-school": {
        /** Creates a new school for the authenticated user and assigns them as ADMIN. Updates user's full_name atomically. */
        post: {
            parameters: {
                body: {
                    /** School registration payload */
                    body: { [key: string]: unknown };
                };
            };
            responses: {
                /** Created */
                201: {
                    schema: { [key: string]: unknown };
                };
                /** Bad Request */
                400: {
                    schema: { [key: string]: unknown };
                };
            };
        };
    };
}

export interface operations {}

export interface external {}
