/**
 * Reports page — role-agnostic route.
 *
 * SCHOOL_ADMIN: report generation dashboard
 * PARENT: list of available term reports for their children
 * TEACHER: minimal — redirects to attendance
 */

import { getVerifiedRole } from "@/lib/auth-server";

export default async function ReportsPage() {
    const role = await getVerifiedRole();

    if (!role) {
        return (
            <article>
                <p>Unable to verify your session. Please log in again.</p>
            </article>
        );
    }

    switch (role) {
        case "SCHOOL_ADMIN":
        case "SYSTEM_ADMIN": {
            // Show admin report overview — terms with generation status
            return (
                <div className="space-y-6">
                    <h1 className="text-2xl font-bold">Reports</h1>
                    <p className="text-muted-foreground">Select a term to manage reports.</p>
                    {/* TODO: List terms with report counts */}
                </div>
            );
        }
        case "PARENT": {
            // Show available term reports for linked children
            return (
                <div className="space-y-6">
                    <h1 className="text-2xl font-bold">Term Reports</h1>
                    <p className="text-muted-foreground">
                        Your child&apos;s term reports will appear here once generated by the
                        school.
                    </p>
                </div>
            );
        }
        default:
            return (
                <article>
                    <p>You do not have access to this page.</p>
                </article>
            );
    }
}
