// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: academic_year_lookup.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAcademicTermRangeBySchool = `-- name: GetAcademicTermRangeBySchool :one
SELECT at.start_date, at.end_date FROM academic_terms at JOIN academic_years ay ON ay.id = at.academic_year_id WHERE ay.school_id = $1 AND at.start_date <= $2 AND at.end_date >= $3 ORDER BY at.start_date DESC LIMIT 1
`

type GetAcademicTermRangeBySchoolParams struct {
	SchoolID  pgtype.UUID `json:"school_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetAcademicTermRangeBySchoolRow struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) GetAcademicTermRangeBySchool(ctx context.Context, arg GetAcademicTermRangeBySchoolParams) (GetAcademicTermRangeBySchoolRow, error) {
	row := q.db.QueryRow(ctx, getAcademicTermRangeBySchool, arg.SchoolID, arg.StartDate, arg.EndDate)
	var i GetAcademicTermRangeBySchoolRow
	err := row.Scan(&i.StartDate, &i.EndDate)
	return i, err
}

const getLatestAcademicYearBySchool = `-- name: GetLatestAcademicYearBySchool :one
SELECT id, start_date FROM academic_years WHERE school_id = $1 ORDER BY start_date DESC LIMIT 1
`

type GetLatestAcademicYearBySchoolRow struct {
	ID        pgtype.UUID `json:"id"`
	StartDate pgtype.Date `json:"start_date"`
}

func (q *Queries) GetLatestAcademicYearBySchool(ctx context.Context, schoolID pgtype.UUID) (GetLatestAcademicYearBySchoolRow, error) {
	row := q.db.QueryRow(ctx, getLatestAcademicYearBySchool, schoolID)
	var i GetLatestAcademicYearBySchoolRow
	err := row.Scan(&i.ID, &i.StartDate)
	return i, err
}
