// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: academic_terms.sql

package sqlc

import (
	"context"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentAcademicTermBySchool = `-- name: GetCurrentAcademicTermBySchool :one
SELECT at.id, at.start_date, at.end_date
FROM academic_terms at
JOIN academic_years ay ON at.academic_year_id = ay.id
WHERE ay.school_id = $1 AND CURRENT_DATE BETWEEN at.start_date AND at.end_date
ORDER BY at.start_date DESC
LIMIT 1
`

const getLatestAcademicTermBySchool = `-- name: GetLatestAcademicTermBySchool :one
SELECT at.id
FROM academic_terms at
JOIN academic_years ay ON at.academic_year_id = ay.id
WHERE ay.school_id = $1
ORDER BY at.start_date DESC
LIMIT 1
`

type AcademicTermRow struct {
	ID        pgtype.UUID `json:"id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}
type AcademicTermIDRow struct {
	ID pgtype.UUID `json:"id"`
}

func (q *Queries) GetCurrentAcademicTermBySchool(ctx context.Context, schoolID pgtype.UUID) (AcademicTermRow, error) {
	row := q.db.QueryRow(ctx, getCurrentAcademicTermBySchool, schoolID)
	var i AcademicTermRow
	if err := row.Scan(&i.ID, &i.StartDate, &i.EndDate); err != nil {
		return AcademicTermRow{}, err
	}
	return i, nil
}

func (q *Queries) GetLatestAcademicTermBySchool(ctx context.Context, schoolID pgtype.UUID) (AcademicTermIDRow, error) {
	row := q.db.QueryRow(ctx, getLatestAcademicTermBySchool, schoolID)
	var i AcademicTermIDRow
	if err := row.Scan(&i.ID); err != nil {
		return AcademicTermIDRow{}, err
	}
	return i, nil
}
