// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: academic_calendar.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAcademicTerm = `-- name: CreateAcademicTerm :one
INSERT INTO academic_terms (academic_year_id, name, start_date, end_date)
VALUES ($1, $2, $3, $4)
RETURNING id, academic_year_id, name, start_date, end_date, created_at, updated_at
`

type CreateAcademicTermParams struct {
	AcademicYearID pgtype.UUID `json:"academic_year_id"`
	Name           string      `json:"name"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateAcademicTerm(ctx context.Context, arg CreateAcademicTermParams) (AcademicTerm, error) {
	row := q.db.QueryRow(ctx, createAcademicTerm,
		arg.AcademicYearID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
	)
	var i AcademicTerm
	err := row.Scan(
		&i.ID,
		&i.AcademicYearID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAcademicYear = `-- name: CreateAcademicYear :one
INSERT INTO academic_years (school_id, name, start_date, end_date)
VALUES ($1, $2, $3, $4)
RETURNING id, school_id, name, start_date, end_date, created_at, updated_at
`

type CreateAcademicYearParams struct {
	SchoolID  pgtype.UUID `json:"school_id"`
	Name      string      `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateAcademicYear(ctx context.Context, arg CreateAcademicYearParams) (AcademicYear, error) {
	row := q.db.QueryRow(ctx, createAcademicYear,
		arg.SchoolID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
	)
	var i AcademicYear
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
