// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attendance.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTimetableAttendance = `-- name: CreateTimetableAttendance :one
INSERT INTO timetable_attendance (school_id, student_id, class_timetable_slot_id, attendance_date, status, remarks, recorded_by_membership_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, school_id, student_id, class_timetable_slot_id, attendance_date, status, remarks, recorded_by_membership_id, created_at, updated_at
`

type CreateTimetableAttendanceParams struct {
	SchoolID               pgtype.UUID               `json:"school_id"`
	StudentID              pgtype.UUID               `json:"student_id"`
	ClassTimetableSlotID   pgtype.UUID               `json:"class_timetable_slot_id"`
	AttendanceDate         pgtype.Date               `json:"attendance_date"`
	Status                 TimetableAttendanceStatus `json:"status"`
	Remarks                pgtype.Text               `json:"remarks"`
	RecordedByMembershipID pgtype.UUID               `json:"recorded_by_membership_id"`
}

func (q *Queries) CreateTimetableAttendance(ctx context.Context, arg CreateTimetableAttendanceParams) (TimetableAttendance, error) {
	row := q.db.QueryRow(ctx, createTimetableAttendance,
		arg.SchoolID,
		arg.StudentID,
		arg.ClassTimetableSlotID,
		arg.AttendanceDate,
		arg.Status,
		arg.Remarks,
		arg.RecordedByMembershipID,
	)
	var i TimetableAttendance
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.StudentID,
		&i.ClassTimetableSlotID,
		&i.AttendanceDate,
		&i.Status,
		&i.Remarks,
		&i.RecordedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTimetableAttendanceBySlotAndDate = `-- name: GetTimetableAttendanceBySlotAndDate :many
SELECT id, school_id, student_id, class_timetable_slot_id, attendance_date, status, remarks, recorded_by_membership_id, created_at, updated_at
FROM timetable_attendance
WHERE class_timetable_slot_id = $1 AND attendance_date = $2
`

type GetTimetableAttendanceBySlotAndDateParams struct {
	ClassTimetableSlotID pgtype.UUID `json:"class_timetable_slot_id"`
	AttendanceDate       pgtype.Date `json:"attendance_date"`
}

func (q *Queries) GetTimetableAttendanceBySlotAndDate(ctx context.Context, arg GetTimetableAttendanceBySlotAndDateParams) ([]TimetableAttendance, error) {
	rows, err := q.db.Query(ctx, getTimetableAttendanceBySlotAndDate, arg.ClassTimetableSlotID, arg.AttendanceDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimetableAttendance
	for rows.Next() {
		var i TimetableAttendance
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.StudentID,
			&i.ClassTimetableSlotID,
			&i.AttendanceDate,
			&i.Status,
			&i.Remarks,
			&i.RecordedByMembershipID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimetableAttendanceByStudentAndDate = `-- name: GetTimetableAttendanceByStudentAndDate :many
SELECT id, school_id, student_id, class_timetable_slot_id, attendance_date, status, remarks, recorded_by_membership_id, created_at, updated_at
FROM timetable_attendance
WHERE student_id = $1 AND attendance_date = $2
`

type GetTimetableAttendanceByStudentAndDateParams struct {
	StudentID      pgtype.UUID `json:"student_id"`
	AttendanceDate pgtype.Date `json:"attendance_date"`
}

func (q *Queries) GetTimetableAttendanceByStudentAndDate(ctx context.Context, arg GetTimetableAttendanceByStudentAndDateParams) ([]TimetableAttendance, error) {
	rows, err := q.db.Query(ctx, getTimetableAttendanceByStudentAndDate, arg.StudentID, arg.AttendanceDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimetableAttendance
	for rows.Next() {
		var i TimetableAttendance
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.StudentID,
			&i.ClassTimetableSlotID,
			&i.AttendanceDate,
			&i.Status,
			&i.Remarks,
			&i.RecordedByMembershipID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
