// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_service.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveSchoolMembershipByUser = `-- name: GetActiveSchoolMembershipByUser :one
SELECT school_id FROM school_memberships WHERE user_id = $1 AND is_active = true LIMIT 1
`

func (q *Queries) GetActiveSchoolMembershipByUser(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getActiveSchoolMembershipByUser, userID)
	var school_id pgtype.UUID
	err := row.Scan(&school_id)
	return school_id, err
}
