// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_lookup.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuthTenantByStytchOrgID = `-- name: GetAuthTenantByStytchOrgID :one
SELECT id FROM tenants WHERE stytch_org_id = $1 LIMIT 1
`

func (q *Queries) GetAuthTenantByStytchOrgID(ctx context.Context, stytchOrgID string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getAuthTenantByStytchOrgID, stytchOrgID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getAuthUserByEmail = `-- name: GetAuthUserByEmail :one
SELECT id FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetAuthUserByEmail(ctx context.Context, email string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getAuthUserByEmail, email)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
