// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bulk_jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBulkJob = `-- name: CreateBulkJob :one
INSERT INTO bulk_jobs (job_type, idempotency_key, school_id, tenant_id, created_by, status, total_records, metadata) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id
`

type CreateBulkJobParams struct {
	JobType        string      `json:"job_type"`
	IdempotencyKey string      `json:"idempotency_key"`
	SchoolID       pgtype.UUID `json:"school_id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	CreatedBy      pgtype.UUID `json:"created_by"`
	Status         string      `json:"status"`
	TotalRecords   int32       `json:"total_records"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateBulkJob(ctx context.Context, arg CreateBulkJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createBulkJob,
		arg.JobType,
		arg.IdempotencyKey,
		arg.SchoolID,
		arg.TenantID,
		arg.CreatedBy,
		arg.Status,
		arg.TotalRecords,
		arg.Metadata,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getBulkJob = `-- name: GetBulkJob :one
SELECT id, job_type, idempotency_key, school_id, tenant_id, created_by, status, total_records, succeeded_count, failed_count, deferred_count, metadata, created_at, updated_at FROM bulk_jobs WHERE id=$1
`

func (q *Queries) GetBulkJob(ctx context.Context, id pgtype.UUID) (BulkJob, error) {
	row := q.db.QueryRow(ctx, getBulkJob, id)
	var i BulkJob
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.IdempotencyKey,
		&i.SchoolID,
		&i.TenantID,
		&i.CreatedBy,
		&i.Status,
		&i.TotalRecords,
		&i.SucceededCount,
		&i.FailedCount,
		&i.DeferredCount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBulkJobByTenantAndIdempotency = `-- name: GetBulkJobByTenantAndIdempotency :one
SELECT id, job_type, idempotency_key, school_id, tenant_id, created_by, status, total_records, succeeded_count, failed_count, deferred_count, metadata, created_at, updated_at FROM bulk_jobs WHERE tenant_id=$1 AND idempotency_key=$2
`

type GetBulkJobByTenantAndIdempotencyParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetBulkJobByTenantAndIdempotency(ctx context.Context, arg GetBulkJobByTenantAndIdempotencyParams) (BulkJob, error) {
	row := q.db.QueryRow(ctx, getBulkJobByTenantAndIdempotency, arg.TenantID, arg.IdempotencyKey)
	var i BulkJob
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.IdempotencyKey,
		&i.SchoolID,
		&i.TenantID,
		&i.CreatedBy,
		&i.Status,
		&i.TotalRecords,
		&i.SucceededCount,
		&i.FailedCount,
		&i.DeferredCount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSchoolMembershipRole = `-- name: GetSchoolMembershipRole :one
SELECT role FROM school_memberships WHERE school_id=$1 AND user_id=$2 AND is_active=true
`

type GetSchoolMembershipRoleParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetSchoolMembershipRole(ctx context.Context, arg GetSchoolMembershipRoleParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, getSchoolMembershipRole, arg.SchoolID, arg.UserID)
	var role UserRole
	err := row.Scan(&role)
	return role, err
}

const getTenantStytchOrgID = `-- name: GetTenantStytchOrgID :one
SELECT stytch_org_id FROM tenants WHERE id=$1
`

func (q *Queries) GetTenantStytchOrgID(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTenantStytchOrgID, id)
	var stytch_org_id string
	err := row.Scan(&stytch_org_id)
	return stytch_org_id, err
}

const incrementBulkJobCounts = `-- name: IncrementBulkJobCounts :exec
UPDATE bulk_jobs SET succeeded_count = succeeded_count + $1, failed_count = failed_count + $2, deferred_count = deferred_count + $3, updated_at = NOW() WHERE id=$4
`

type IncrementBulkJobCountsParams struct {
	SucceededCount int32       `json:"succeeded_count"`
	FailedCount    int32       `json:"failed_count"`
	DeferredCount  int32       `json:"deferred_count"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) IncrementBulkJobCounts(ctx context.Context, arg IncrementBulkJobCountsParams) error {
	_, err := q.db.Exec(ctx, incrementBulkJobCounts,
		arg.SucceededCount,
		arg.FailedCount,
		arg.DeferredCount,
		arg.ID,
	)
	return err
}

const updateBulkJobStatus = `-- name: UpdateBulkJobStatus :exec
UPDATE bulk_jobs SET status=$1, updated_at=NOW() WHERE id=$2
`

type UpdateBulkJobStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateBulkJobStatus(ctx context.Context, arg UpdateBulkJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateBulkJobStatus, arg.Status, arg.ID)
	return err
}
