// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: class_timetable_slots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClassTimetableSlot = `-- name: CreateClassTimetableSlot :one
INSERT INTO class_timetable_slots (school_id, class_room_id, academic_term_id, day_of_week, time_slot_id, subject_id, teacher_membership_id, room_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateClassTimetableSlotParams struct {
	SchoolID            pgtype.UUID `json:"school_id"`
	ClassRoomID         pgtype.UUID `json:"class_room_id"`
	AcademicTermID      pgtype.UUID `json:"academic_term_id"`
	DayOfWeek           int32       `json:"day_of_week"`
	TimeSlotID          pgtype.UUID `json:"time_slot_id"`
	SubjectID           pgtype.UUID `json:"subject_id"`
	TeacherMembershipID pgtype.UUID `json:"teacher_membership_id"`
	RoomID              pgtype.UUID `json:"room_id"`
}

func (q *Queries) CreateClassTimetableSlot(ctx context.Context, arg CreateClassTimetableSlotParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createClassTimetableSlot,
		arg.SchoolID,
		arg.ClassRoomID,
		arg.AcademicTermID,
		arg.DayOfWeek,
		arg.TimeSlotID,
		arg.SubjectID,
		arg.TeacherMembershipID,
		arg.RoomID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteClassTimetableSlot = `-- name: DeleteClassTimetableSlot :exec
DELETE FROM class_timetable_slots WHERE id = $1
`

func (q *Queries) DeleteClassTimetableSlot(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClassTimetableSlot, id)
	return err
}

const getClassTimetableSlotsByTemplate = `-- name: GetClassTimetableSlotsByTemplate :many
SELECT
  cts.id,
  cts.school_id,
  cts.class_room_id,
  cts.academic_term_id,
  cts.day_of_week,
  cts.time_slot_id,
  cts.subject_id,
  cts.teacher_membership_id,
  cts.room_id,
  cts.created_at,
  cts.updated_at,
  ts.name AS time_slot_name,
  ts.start_time,
  ts.end_time,
  ts.sequence_index,
  ts.is_instructional
FROM class_timetable_slots cts
JOIN time_slots ts ON ts.id = cts.time_slot_id
WHERE cts.class_room_id = $1
  AND ts.timetable_template_id = $2
ORDER BY cts.day_of_week ASC, ts.sequence_index ASC
`

type GetClassTimetableSlotsByTemplateParams struct {
	ClassRoomID         pgtype.UUID `json:"class_room_id"`
	TimetableTemplateID pgtype.UUID `json:"timetable_template_id"`
}

type GetClassTimetableSlotsByTemplateRow struct {
	ID                  pgtype.UUID        `json:"id"`
	SchoolID            pgtype.UUID        `json:"school_id"`
	ClassRoomID         pgtype.UUID        `json:"class_room_id"`
	AcademicTermID      pgtype.UUID        `json:"academic_term_id"`
	DayOfWeek           int32              `json:"day_of_week"`
	TimeSlotID          pgtype.UUID        `json:"time_slot_id"`
	SubjectID           pgtype.UUID        `json:"subject_id"`
	TeacherMembershipID pgtype.UUID        `json:"teacher_membership_id"`
	RoomID              pgtype.UUID        `json:"room_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TimeSlotName        string             `json:"time_slot_name"`
	StartTime           pgtype.Time        `json:"start_time"`
	EndTime             pgtype.Time        `json:"end_time"`
	SequenceIndex       int32              `json:"sequence_index"`
	IsInstructional     bool               `json:"is_instructional"`
}

func (q *Queries) GetClassTimetableSlotsByTemplate(ctx context.Context, arg GetClassTimetableSlotsByTemplateParams) ([]GetClassTimetableSlotsByTemplateRow, error) {
	rows, err := q.db.Query(ctx, getClassTimetableSlotsByTemplate, arg.ClassRoomID, arg.TimetableTemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClassTimetableSlotsByTemplateRow
	for rows.Next() {
		var i GetClassTimetableSlotsByTemplateRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.ClassRoomID,
			&i.AcademicTermID,
			&i.DayOfWeek,
			&i.TimeSlotID,
			&i.SubjectID,
			&i.TeacherMembershipID,
			&i.RoomID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TimeSlotName,
			&i.StartTime,
			&i.EndTime,
			&i.SequenceIndex,
			&i.IsInstructional,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClassTimetableSlotsByTemplateWithDetails = `-- name: GetClassTimetableSlotsByTemplateWithDetails :many
SELECT
  cts.id,
  cts.school_id,
  cts.class_room_id,
  cts.academic_term_id,
  cts.day_of_week,
  cts.time_slot_id,
  cts.subject_id,
  cts.teacher_membership_id,
  cts.room_id,
  cts.created_at,
  cts.updated_at,
  cr.name AS class_name,
  cr.stream AS class_stream,
  gl.local_label AS grade_name,
  ts.name AS time_slot_name,
  ts.start_time,
  ts.end_time,
  ts.sequence_index,
  ts.is_instructional,
  s.name AS subject_name,
  u.full_name AS teacher_name,
  u.email AS teacher_email,
  r.name AS room_name
FROM class_timetable_slots cts
JOIN time_slots ts ON ts.id = cts.time_slot_id
JOIN class_rooms cr ON cr.id = cts.class_room_id
LEFT JOIN grade_levels gl ON gl.id = cr.grade_level_id
LEFT JOIN subjects s ON s.id = cts.subject_id
LEFT JOIN school_memberships sm ON sm.id = cts.teacher_membership_id
LEFT JOIN users u ON u.id = sm.user_id
LEFT JOIN rooms r ON r.id = cts.room_id
WHERE cts.class_room_id = $1
  AND ts.timetable_template_id = $2
ORDER BY cts.day_of_week ASC, ts.sequence_index ASC
`

type GetClassTimetableSlotsByTemplateWithDetailsParams struct {
	ClassRoomID         pgtype.UUID `json:"class_room_id"`
	TimetableTemplateID pgtype.UUID `json:"timetable_template_id"`
}

type GetClassTimetableSlotsByTemplateWithDetailsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	SchoolID            pgtype.UUID        `json:"school_id"`
	ClassRoomID         pgtype.UUID        `json:"class_room_id"`
	AcademicTermID      pgtype.UUID        `json:"academic_term_id"`
	DayOfWeek           int32              `json:"day_of_week"`
	TimeSlotID          pgtype.UUID        `json:"time_slot_id"`
	SubjectID           pgtype.UUID        `json:"subject_id"`
	TeacherMembershipID pgtype.UUID        `json:"teacher_membership_id"`
	RoomID              pgtype.UUID        `json:"room_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ClassName           string             `json:"class_name"`
	ClassStream         pgtype.Text        `json:"class_stream"`
	GradeName           pgtype.Text        `json:"grade_name"`
	TimeSlotName        string             `json:"time_slot_name"`
	StartTime           pgtype.Time        `json:"start_time"`
	EndTime             pgtype.Time        `json:"end_time"`
	SequenceIndex       int32              `json:"sequence_index"`
	IsInstructional     bool               `json:"is_instructional"`
	SubjectName         pgtype.Text        `json:"subject_name"`
	TeacherName         pgtype.Text        `json:"teacher_name"`
	TeacherEmail        pgtype.Text        `json:"teacher_email"`
	RoomName            pgtype.Text        `json:"room_name"`
}

func (q *Queries) GetClassTimetableSlotsByTemplateWithDetails(ctx context.Context, arg GetClassTimetableSlotsByTemplateWithDetailsParams) ([]GetClassTimetableSlotsByTemplateWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, getClassTimetableSlotsByTemplateWithDetails, arg.ClassRoomID, arg.TimetableTemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClassTimetableSlotsByTemplateWithDetailsRow
	for rows.Next() {
		var i GetClassTimetableSlotsByTemplateWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.ClassRoomID,
			&i.AcademicTermID,
			&i.DayOfWeek,
			&i.TimeSlotID,
			&i.SubjectID,
			&i.TeacherMembershipID,
			&i.RoomID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClassName,
			&i.ClassStream,
			&i.GradeName,
			&i.TimeSlotName,
			&i.StartTime,
			&i.EndTime,
			&i.SequenceIndex,
			&i.IsInstructional,
			&i.SubjectName,
			&i.TeacherName,
			&i.TeacherEmail,
			&i.RoomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
