// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: class_lookup.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentAcademicYearBySchool = `-- name: GetCurrentAcademicYearBySchool :one
SELECT id FROM academic_years WHERE school_id = $1 ORDER BY start_date DESC LIMIT 1
`

func (q *Queries) GetCurrentAcademicYearBySchool(ctx context.Context, schoolID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCurrentAcademicYearBySchool, schoolID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
