// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: class_timetable_slots.sql

package sqlc

import (
	"context"
	"github.com/jackc/pgx/v5/pgtype"
)

const createClassTimetableSlot = `-- name: CreateClassTimetableSlot :one
INSERT INTO class_timetable_slots (school_id, class_room_id, academic_term_id, day_of_week, time_slot_id, subject_id, teacher_membership_id, room_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateClassTimetableSlotParams struct {
	SchoolID            pgtype.UUID `json:"school_id"`
	ClassRoomID         pgtype.UUID `json:"class_room_id"`
	AcademicTermID      pgtype.UUID `json:"academic_term_id"`
	DayOfWeek           int32       `json:"day_of_week"`
	TimeSlotID          pgtype.UUID `json:"time_slot_id"`
	SubjectID           pgtype.UUID `json:"subject_id"`
	TeacherMembershipID pgtype.UUID `json:"teacher_membership_id"`
	RoomID              pgtype.UUID `json:"room_id"`
}

func (q *Queries) CreateClassTimetableSlot(ctx context.Context, arg CreateClassTimetableSlotParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createClassTimetableSlot,
		arg.SchoolID,
		arg.ClassRoomID,
		arg.AcademicTermID,
		arg.DayOfWeek,
		arg.TimeSlotID,
		arg.SubjectID,
		arg.TeacherMembershipID,
		arg.RoomID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
