// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: countries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCountryByName = `-- name: GetCountryByName :one
SELECT id FROM countries WHERE country_name = $1 LIMIT 1
`

func (q *Queries) GetCountryByName(ctx context.Context, countryName string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCountryByName, countryName)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getEducationSystemByCountryAndName = `-- name: GetEducationSystemByCountryAndName :one
SELECT id FROM education_systems WHERE country_id = $1 AND system_name ILIKE $2 LIMIT 1
`

type GetEducationSystemByCountryAndNameParams struct {
	CountryID  pgtype.UUID `json:"country_id"`
	SystemName string      `json:"system_name"`
}

func (q *Queries) GetEducationSystemByCountryAndName(ctx context.Context, arg GetEducationSystemByCountryAndNameParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getEducationSystemByCountryAndName, arg.CountryID, arg.SystemName)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
