// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grade_levels.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGradeLevelByID = `-- name: GetGradeLevelByID :one
SELECT id, country_id, education_system_id, local_label FROM grade_levels WHERE id = $1
`

type GetGradeLevelByIDRow struct {
	ID                pgtype.UUID `json:"id"`
	CountryID         pgtype.UUID `json:"country_id"`
	EducationSystemID pgtype.UUID `json:"education_system_id"`
	LocalLabel        string      `json:"local_label"`
}

func (q *Queries) GetGradeLevelByID(ctx context.Context, id pgtype.UUID) (GetGradeLevelByIDRow, error) {
	row := q.db.QueryRow(ctx, getGradeLevelByID, id)
	var i GetGradeLevelByIDRow
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.EducationSystemID,
		&i.LocalLabel,
	)
	return i, err
}
