// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guardians.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGuardianSummary = `-- name: GetGuardianSummary :one
SELECT
  COUNT(*) AS total_guardians,
  COUNT(*) FILTER (WHERE NOT EXISTS (
    SELECT 1 FROM guardian_student_links gsl WHERE gsl.school_membership_id = sm.id
  )) AS guardians_without_student
FROM school_memberships sm
WHERE sm.school_id = $1 AND sm.role = 'GUARDIAN' AND sm.is_active = true
`

type GetGuardianSummaryRow struct {
	TotalGuardians          int64 `json:"total_guardians"`
	GuardiansWithoutStudent int64 `json:"guardians_without_student"`
}

func (q *Queries) GetGuardianSummary(ctx context.Context, schoolID pgtype.UUID) (GetGuardianSummaryRow, error) {
	row := q.db.QueryRow(ctx, getGuardianSummary, schoolID)
	var i GetGuardianSummaryRow
	err := row.Scan(&i.TotalGuardians, &i.GuardiansWithoutStudent)
	return i, err
}
