// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guardians.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGuardians = `-- name: CountGuardians :one
SELECT COUNT(*)
FROM school_memberships sm
JOIN users u ON u.id = sm.user_id
WHERE sm.school_id = $1
  AND sm.role = 'GUARDIAN'
  AND ($2::text = '' OR u.email ILIKE '%' || $2 || '%' OR u.full_name ILIKE '%' || $2 || '%')
  AND (
    $3::text = '' OR
    ($3 = 'invited' AND sm.invited_at IS NOT NULL AND sm.accepted_at IS NULL) OR
    ($3 = 'accepted' AND sm.accepted_at IS NOT NULL)
  )
`

type CountGuardiansParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Column2  string      `json:"column_2"`
	Column3  string      `json:"column_3"`
}

func (q *Queries) CountGuardians(ctx context.Context, arg CountGuardiansParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGuardians, arg.SchoolID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGuardians = `-- name: DeleteGuardians :exec
DELETE FROM school_memberships
WHERE school_id = $1 AND user_id = ANY($2::uuid[]) AND role = 'GUARDIAN'
`

type DeleteGuardiansParams struct {
	SchoolID pgtype.UUID   `json:"school_id"`
	Column2  []pgtype.UUID `json:"column_2"`
}

func (q *Queries) DeleteGuardians(ctx context.Context, arg DeleteGuardiansParams) error {
	_, err := q.db.Exec(ctx, deleteGuardians, arg.SchoolID, arg.Column2)
	return err
}

const getGuardianSummary = `-- name: GetGuardianSummary :one
SELECT
  COUNT(*) AS total_guardians,
  COUNT(*) FILTER (WHERE NOT EXISTS (
    SELECT 1 FROM guardian_student_links gsl WHERE gsl.school_membership_id = sm.id
  )) AS guardians_without_student
FROM school_memberships sm
WHERE sm.school_id = $1 AND sm.role = 'GUARDIAN' AND sm.is_active = true
`

type GetGuardianSummaryRow struct {
	TotalGuardians          int64 `json:"total_guardians"`
	GuardiansWithoutStudent int64 `json:"guardians_without_student"`
}

func (q *Queries) GetGuardianSummary(ctx context.Context, schoolID pgtype.UUID) (GetGuardianSummaryRow, error) {
	row := q.db.QueryRow(ctx, getGuardianSummary, schoolID)
	var i GetGuardianSummaryRow
	err := row.Scan(&i.TotalGuardians, &i.GuardiansWithoutStudent)
	return i, err
}

const listGuardians = `-- name: ListGuardians :many
SELECT sm.id, sm.user_id, u.email, u.full_name, sm.invited_at, sm.accepted_at, sm.is_active, sm.created_at
FROM school_memberships sm
JOIN users u ON u.id = sm.user_id
WHERE sm.school_id = $1
  AND sm.role = 'GUARDIAN'
  AND ($2::text = '' OR u.email ILIKE '%' || $2 || '%' OR u.full_name ILIKE '%' || $2 || '%')
  AND (
    $3::text = '' OR
    ($3 = 'invited' AND sm.invited_at IS NOT NULL AND sm.accepted_at IS NULL) OR
    ($3 = 'accepted' AND sm.accepted_at IS NOT NULL)
  )
ORDER BY sm.created_at DESC
LIMIT $4 OFFSET $5
`

type ListGuardiansParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Column2  string      `json:"column_2"`
	Column3  string      `json:"column_3"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListGuardiansRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Email      string             `json:"email"`
	FullName   string             `json:"full_name"`
	InvitedAt  pgtype.Timestamptz `json:"invited_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListGuardians(ctx context.Context, arg ListGuardiansParams) ([]ListGuardiansRow, error) {
	rows, err := q.db.Query(ctx, listGuardians,
		arg.SchoolID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuardiansRow
	for rows.Next() {
		var i ListGuardiansRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.FullName,
			&i.InvitedAt,
			&i.AcceptedAt,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
