// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (stytch_member_id, user_id, tenant_id, stytch_member_raw)
VALUES ($1, $2, $3, $4)
RETURNING id, stytch_member_id, user_id, tenant_id, stytch_member_raw, created_at, updated_at
`

type CreateMemberParams struct {
	StytchMemberID  string      `json:"stytch_member_id"`
	UserID          pgtype.UUID `json:"user_id"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	StytchMemberRaw []byte      `json:"stytch_member_raw"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.StytchMemberID,
		arg.UserID,
		arg.TenantID,
		arg.StytchMemberRaw,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.StytchMemberID,
		&i.UserID,
		&i.TenantID,
		&i.StytchMemberRaw,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberByStytchMemberID = `-- name: GetMemberByStytchMemberID :one
SELECT
    id,
    stytch_member_id,
    user_id,
    tenant_id,
    stytch_member_raw,
    created_at,
    updated_at
FROM members
WHERE stytch_member_id = $1
LIMIT 1
`

func (q *Queries) GetMemberByStytchMemberID(ctx context.Context, stytchMemberID string) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByStytchMemberID, stytchMemberID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.StytchMemberID,
		&i.UserID,
		&i.TenantID,
		&i.StytchMemberRaw,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
