// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Maps 1:1 to a Stytch OIDC organization. All Somotracker data is scoped under exactly one tenant row.
type Tenant struct {
	// Auto-generated UUID primary key. No external meaning — treat as opaque.
	ID pgtype.UUID `json:"id"`
	// Human-readable organization display name (e.g. "Acme Corp").
	Name string `json:"name"`
	// URL-safe, lowercase, hyphen-separated identifier. Used for subdomains and admin routing. Must be globally unique.
	Slug string `json:"slug"`
	// The Stytch OIDC organization ID. This is the authoritative identity anchor for SSO / SAML membership. Unique.
	StytchOrgID string `json:"stytch_org_id"`
	// UTC timestamp of row creation.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Per-tenant user accounts. Rows are scoped to exactly one tenant via the foreign key on tenant_id. Users are identified by email within a tenant scope; the same email may appear in different tenants.
type User struct {
	// Auto-generated UUID primary key. No external meaning — treat as opaque.
	ID pgtype.UUID `json:"id"`
	// Canonical email address. Lowercase (enforced by CHECK), unique within a tenant but not globally via users_tenant_email_uniq.
	Email string `json:"email"`
	// Foreign key to tenants(id). Every user must belong to exactly one tenant. Deleting the tenant cascades this row.
	TenantID pgtype.UUID `json:"tenant_id"`
	// Display name chosen by the user. May be empty.
	FullName string `json:"full_name"`
	// Soft-disable flag. Inactive users cannot authenticate but their rows are retained for audit purposes.
	IsActive bool `json:"is_active"`
	// Stytch user ID or equivalent auth-provider subject. Enables linking the local row to the external identity without querying by email.
	ExternalAuthID pgtype.Text `json:"external_auth_id"`
	// UTC timestamp of row creation.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// UTC timestamp of last modification (updated by application code, not triggers by default).
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Server-issued opaque session tokens. Tokens are stored in HttpOnly cookies; the raw Stytch session token is cached only in Redis.
type Session struct {
	// Auto-generated UUID primary key.
	ID pgtype.UUID `json:"id"`
	// Opaque 256-bit token, hex-encoded. Never exposed to JavaScript or URLs.
	Token string `json:"token"`
	// Opaque Stytch session ID used for revocation / validation against Stytch.
	StytchSessionID string `json:"stytch_session_id"`
	// FK to users(id). Deleting the user cascades all sessions.
	UserID pgtype.UUID `json:"user_id"`
	// FK to tenants(id). Used for fast tenant-scoped session lookup.
	TenantID pgtype.UUID `json:"tenant_id"`
	// Rolling expiry timestamp. Default 7 days.
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// UTC timestamp of session creation.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// UTC timestamp of last validated request. Used for rolling expiry refresh.
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

// B2B member identity mirroring Stytch. Created/updated atomically with users during magic-link provisioning.
type Member struct {
	// Auto-generated UUID primary key.
	ID pgtype.UUID `json:"id"`
	// Stytch B2B Member.member_id. Unique across the entire system.
	StytchMemberID string `json:"stytch_member_id"`
	// FK to users(id). The Somotracker application identity.
	UserID pgtype.UUID `json:"user_id"`
	// FK to tenants(id). The B2B organization.
	TenantID pgtype.UUID `json:"tenant_id"`
	// Array of Somotracker role names. Somotracker currently uses: admin, member.
	Roles []string `json:"roles"`
	// Cached Stytch member object (JSONB) for audit/debugging.
	StytchMemberRaw []byte `json:"stytch_member_raw"`
	// UTC timestamp of member creation.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// UTC timestamp of last modification.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
