// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Maps 1:1 to a Stytch OIDC organization. All Somotracker data is scoped under exactly one tenant row.
type Tenant struct {
	// Auto-generated UUID primary key. No external meaning — treat as opaque.
	ID pgtype.UUID `json:"id"`
	// Human-readable organization display name (e.g. "Acme Corp").
	Name string `json:"name"`
	// URL-safe, lowercase, hyphen-separated identifier. Used for subdomains and admin routing. Must be globally unique.
	Slug string `json:"slug"`
	// The Stytch OIDC organization ID. This is the authoritative identity anchor for SSO / SAML membership. Unique.
	StytchOrgID string `json:"stytch_org_id"`
	// UTC timestamp of row creation.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Per-tenant user accounts. Rows are scoped to exactly one tenant via the foreign key on tenant_id. Users are identified by email within a tenant scope; the same email may appear in different tenants.
type User struct {
	// Auto-generated UUID primary key. No external meaning — treat as opaque.
	ID pgtype.UUID `json:"id"`
	// Canonical email address. Lowercase (enforced by CHECK), unique within a tenant but not globally via users_tenant_email_uniq.
	Email string `json:"email"`
	// Foreign key to tenants(id). Every user must belong to exactly one tenant. Deleting the tenant cascades this row.
	TenantID pgtype.UUID `json:"tenant_id"`
	// Display name chosen by the user. May be empty.
	FullName string `json:"full_name"`
	// Soft-disable flag. Inactive users cannot authenticate but their rows are retained for audit purposes.
	IsActive bool `json:"is_active"`
	// Stytch user ID or equivalent auth-provider subject. Enables linking the local row to the external identity without querying by email.
	ExternalAuthID pgtype.Text `json:"external_auth_id"`
	// UTC timestamp of row creation.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// UTC timestamp of last modification (updated by application code, not triggers by default).
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
