// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAcademicTerm(ctx context.Context, arg CreateAcademicTermParams) (AcademicTerm, error)
	CreateAcademicYear(ctx context.Context, arg CreateAcademicYearParams) (AcademicYear, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStream(ctx context.Context, arg CreateStreamParams) (Stream, error)
	DeleteSession(ctx context.Context, token string) error
	GetMemberByStytchMemberID(ctx context.Context, stytchMemberID string) (Member, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetTenantByStytchOrgID(ctx context.Context, stytchOrgID string) (Tenant, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	// Updates invitation/acceptance timestamps and role for an existing membership.
	UpdateMembershipInvitationState(ctx context.Context, arg UpdateMembershipInvitationStateParams) error
	UpdateSessionLastSeen(ctx context.Context, id pgtype.UUID) error
	// Upserts (or updates) a school_membership during bulk invitation.
	// On conflict over the school/user unique constraint, updates invitation state,
	// role, active flag, and invitation metadata. Returns the full row.
	UpsertSchoolMembership(ctx context.Context, arg UpsertSchoolMembershipParams) (UpsertSchoolMembershipRow, error)
}

var _ Querier = (*Queries)(nil)
