// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountSearchSubjects(ctx context.Context, name string) (int64, error)
	CountStudents(ctx context.Context, arg CountStudentsParams) (int64, error)
	CountSubTopicsByTopic(ctx context.Context, topicID pgtype.UUID) (int64, error)
	CountSubjects(ctx context.Context) (int64, error)
	CountTopicsBySubject(ctx context.Context, subjectID pgtype.UUID) (int64, error)
	CreateAcademicTerm(ctx context.Context, arg CreateAcademicTermParams) (AcademicTerm, error)
	CreateAcademicYear(ctx context.Context, arg CreateAcademicYearParams) (AcademicYear, error)
	CreateBulkJob(ctx context.Context, arg CreateBulkJobParams) (pgtype.UUID, error)
	CreateClassTimetableSlot(ctx context.Context, arg CreateClassTimetableSlotParams) (pgtype.UUID, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStream(ctx context.Context, arg CreateStreamParams) (Stream, error)
	CreateTimeSlot(ctx context.Context, arg CreateTimeSlotParams) (pgtype.UUID, error)
	CreateTimetableAttendance(ctx context.Context, arg CreateTimetableAttendanceParams) (TimetableAttendance, error)
	CreateTimetableTemplate(ctx context.Context, arg CreateTimetableTemplateParams) (pgtype.UUID, error)
	DeleteClassTimetableSlot(ctx context.Context, id pgtype.UUID) error
	DeleteRoom(ctx context.Context, arg DeleteRoomParams) error
	DeleteSession(ctx context.Context, token string) error
	DeleteStudents(ctx context.Context, arg DeleteStudentsParams) error
	GetAcademicTermRangeBySchool(ctx context.Context, arg GetAcademicTermRangeBySchoolParams) (GetAcademicTermRangeBySchoolRow, error)
	GetActiveSchoolMembershipByUser(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error)
	GetAuthTenantByStytchOrgID(ctx context.Context, stytchOrgID string) (pgtype.UUID, error)
	GetAuthUserByEmail(ctx context.Context, email string) (pgtype.UUID, error)
	GetBulkJob(ctx context.Context, id pgtype.UUID) (BulkJob, error)
	GetBulkJobByTenantAndIdempotency(ctx context.Context, arg GetBulkJobByTenantAndIdempotencyParams) (BulkJob, error)
	GetClassTimetableSlotsByTemplate(ctx context.Context, arg GetClassTimetableSlotsByTemplateParams) ([]GetClassTimetableSlotsByTemplateRow, error)
	GetClassTimetableSlotsByTemplateWithDetails(ctx context.Context, arg GetClassTimetableSlotsByTemplateWithDetailsParams) ([]GetClassTimetableSlotsByTemplateWithDetailsRow, error)
	GetCountryByName(ctx context.Context, countryName string) (pgtype.UUID, error)
	GetCurrentAcademicYearBySchool(ctx context.Context, schoolID pgtype.UUID) (pgtype.UUID, error)
	GetEducationSystemByCountryAndName(ctx context.Context, arg GetEducationSystemByCountryAndNameParams) (pgtype.UUID, error)
	GetGradeLevelByID(ctx context.Context, id pgtype.UUID) (GetGradeLevelByIDRow, error)
	GetGuardianSummary(ctx context.Context, schoolID pgtype.UUID) (GetGuardianSummaryRow, error)
	GetLatestAcademicYearBySchool(ctx context.Context, schoolID pgtype.UUID) (GetLatestAcademicYearBySchoolRow, error)
	GetMemberByStytchMemberID(ctx context.Context, stytchMemberID string) (Member, error)
	// Gets a school membership by user_id and school_id.
	GetSchoolMembershipByUserAndSchool(ctx context.Context, arg GetSchoolMembershipByUserAndSchoolParams) (GetSchoolMembershipByUserAndSchoolRow, error)
	GetSchoolMembershipRole(ctx context.Context, arg GetSchoolMembershipRoleParams) (UserRole, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetStream(ctx context.Context, id pgtype.UUID) (GetStreamRow, error)
	GetStudentSummary(ctx context.Context, arg GetStudentSummaryParams) (GetStudentSummaryRow, error)
	GetSubTopicByID(ctx context.Context, id pgtype.UUID) (GetSubTopicByIDRow, error)
	GetSubjectByID(ctx context.Context, id pgtype.UUID) (GetSubjectByIDRow, error)
	GetTeacherSummary(ctx context.Context, arg GetTeacherSummaryParams) (GetTeacherSummaryRow, error)
	GetTenantByStytchOrgID(ctx context.Context, stytchOrgID string) (Tenant, error)
	GetTenantStytchOrgID(ctx context.Context, id pgtype.UUID) (string, error)
	GetTimetableAttendanceBySlotAndDate(ctx context.Context, arg GetTimetableAttendanceBySlotAndDateParams) ([]TimetableAttendance, error)
	GetTimetableAttendanceByStudentAndDate(ctx context.Context, arg GetTimetableAttendanceByStudentAndDateParams) ([]TimetableAttendance, error)
	GetTimetableTemplate(ctx context.Context, id pgtype.UUID) (TimetableTemplate, error)
	GetTopicByID(ctx context.Context, id pgtype.UUID) (GetTopicByIDRow, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	IncrementBulkJobCounts(ctx context.Context, arg IncrementBulkJobCountsParams) error
	ListRoomsBySchool(ctx context.Context, schoolID pgtype.UUID) ([]Room, error)
	ListStreamsBySchool(ctx context.Context, schoolID pgtype.UUID) ([]Stream, error)
	ListStudents(ctx context.Context, arg ListStudentsParams) ([]ListStudentsRow, error)
	ListSubTopics(ctx context.Context, arg ListSubTopicsParams) ([]ListSubTopicsRow, error)
	ListSubTopicsByTopic(ctx context.Context, topicID pgtype.UUID) ([]ListSubTopicsByTopicRow, error)
	ListSubjects(ctx context.Context, arg ListSubjectsParams) ([]ListSubjectsRow, error)
	ListSubjectsBySystem(ctx context.Context, educationSystemID pgtype.UUID) ([]ListSubjectsBySystemRow, error)
	ListTimeSlotsByTemplate(ctx context.Context, timetableTemplateID pgtype.UUID) ([]TimeSlot, error)
	ListTimetableTemplatesBySchool(ctx context.Context, schoolID pgtype.UUID) ([]TimetableTemplate, error)
	ListTopics(ctx context.Context, arg ListTopicsParams) ([]ListTopicsRow, error)
	ListTopicsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]ListTopicsBySubjectRow, error)
	SearchSubjects(ctx context.Context, arg SearchSubjectsParams) ([]SearchSubjectsRow, error)
	UpdateBulkJobStatus(ctx context.Context, arg UpdateBulkJobStatusParams) error
	// Updates invitation/acceptance timestamps and role for an existing membership.
	UpdateMembershipInvitationState(ctx context.Context, arg UpdateMembershipInvitationStateParams) error
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error)
	UpdateSessionLastSeen(ctx context.Context, id pgtype.UUID) error
	UpdateTimetableTemplate(ctx context.Context, arg UpdateTimetableTemplateParams) error
	// Upserts (or updates) a school_membership during bulk invitation.
	// On conflict over the school/user unique constraint, updates invitation state,
	// role, active flag, and invitation metadata. Returns the full row.
	UpsertSchoolMembership(ctx context.Context, arg UpsertSchoolMembershipParams) (UpsertSchoolMembershipRow, error)
}

var _ Querier = (*Queries)(nil)
