// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (school_id, name, capacity, room_type)
VALUES ($1, $2, $3, $4)
RETURNING id, school_id, name, capacity, room_type, created_at, updated_at
`

type CreateRoomParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Name     string      `json:"name"`
	Capacity pgtype.Int4 `json:"capacity"`
	RoomType RoomType    `json:"room_type"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.SchoolID,
		arg.Name,
		arg.Capacity,
		arg.RoomType,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.Capacity,
		&i.RoomType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE id = $1 AND school_id = $2
`

type DeleteRoomParams struct {
	ID       pgtype.UUID `json:"id"`
	SchoolID pgtype.UUID `json:"school_id"`
}

func (q *Queries) DeleteRoom(ctx context.Context, arg DeleteRoomParams) error {
	_, err := q.db.Exec(ctx, deleteRoom, arg.ID, arg.SchoolID)
	return err
}

const listRoomsBySchool = `-- name: ListRoomsBySchool :many
SELECT id, school_id, name, capacity, room_type, created_at, updated_at
FROM rooms
WHERE school_id = $1
ORDER BY name ASC
`

func (q *Queries) ListRoomsBySchool(ctx context.Context, schoolID pgtype.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRoomsBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Name,
			&i.Capacity,
			&i.RoomType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET name = COALESCE(NULLIF($3::text, ''), name),
    capacity = COALESCE($4, capacity),
    room_type = COALESCE(NULLIF($5::text, ''), room_type),
    updated_at = NOW()
WHERE id = $1 AND school_id = $2
RETURNING id, school_id, name, capacity, room_type, created_at, updated_at
`

type UpdateRoomParams struct {
	ID       pgtype.UUID `json:"id"`
	SchoolID pgtype.UUID `json:"school_id"`
	Column3  string      `json:"column_3"`
	Capacity pgtype.Int4 `json:"capacity"`
	Column5  string      `json:"column_5"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.ID,
		arg.SchoolID,
		arg.Column3,
		arg.Capacity,
		arg.Column5,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.Capacity,
		&i.RoomType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
