// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: school_memberships.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateMembershipInvitationState = `-- name: UpdateMembershipInvitationState :exec
UPDATE school_memberships
SET
    invited_at = $1,
    invited_by = $2,
    accepted_at = $3,
    role = $4,
    is_active = $5,
    updated_at = NOW()
WHERE id = $6
`

type UpdateMembershipInvitationStateParams struct {
	InvitedAt  pgtype.Timestamptz `json:"invited_at"`
	InvitedBy  pgtype.UUID        `json:"invited_by"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	Role       UserRole           `json:"role"`
	IsActive   bool               `json:"is_active"`
	ID         pgtype.UUID        `json:"id"`
}

// Updates invitation/acceptance timestamps and role for an existing membership.
func (q *Queries) UpdateMembershipInvitationState(ctx context.Context, arg UpdateMembershipInvitationStateParams) error {
	_, err := q.db.Exec(ctx, updateMembershipInvitationState,
		arg.InvitedAt,
		arg.InvitedBy,
		arg.AcceptedAt,
		arg.Role,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const upsertSchoolMembership = `-- name: UpsertSchoolMembership :one
INSERT INTO school_memberships (
    school_id,
    user_id,
    role,
    is_active,
    invited_at,
    invited_by,
    accepted_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (school_id, user_id) DO UPDATE SET
    role = EXCLUDED.role,
    is_active = EXCLUDED.is_active,
    invited_at = EXCLUDED.invited_at,
    invited_by = EXCLUDED.invited_by,
    accepted_at = EXCLUDED.accepted_at,
    updated_at = NOW()
RETURNING id, school_id, user_id, role, is_active, invited_at, invited_by, accepted_at, created_at, updated_at
`

type UpsertSchoolMembershipParams struct {
	SchoolID   pgtype.UUID        `json:"school_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Role       UserRole           `json:"role"`
	IsActive   bool               `json:"is_active"`
	InvitedAt  pgtype.Timestamptz `json:"invited_at"`
	InvitedBy  pgtype.UUID        `json:"invited_by"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
}

type UpsertSchoolMembershipRow struct {
	ID         pgtype.UUID        `json:"id"`
	SchoolID   pgtype.UUID        `json:"school_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Role       UserRole           `json:"role"`
	IsActive   bool               `json:"is_active"`
	InvitedAt  pgtype.Timestamptz `json:"invited_at"`
	InvitedBy  pgtype.UUID        `json:"invited_by"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Upserts (or updates) a school_membership during bulk invitation.
// On conflict over the school/user unique constraint, updates invitation state,
// role, active flag, and invitation metadata. Returns the full row.
func (q *Queries) UpsertSchoolMembership(ctx context.Context, arg UpsertSchoolMembershipParams) (UpsertSchoolMembershipRow, error) {
	row := q.db.QueryRow(ctx, upsertSchoolMembership,
		arg.SchoolID,
		arg.UserID,
		arg.Role,
		arg.IsActive,
		arg.InvitedAt,
		arg.InvitedBy,
		arg.AcceptedAt,
	)
	var i UpsertSchoolMembershipRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.UserID,
		&i.Role,
		&i.IsActive,
		&i.InvitedAt,
		&i.InvitedBy,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
