// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token, stytch_session_id, user_id, tenant_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, token, stytch_session_id, user_id, tenant_id, expires_at, created_at, last_seen_at
`

type CreateSessionParams struct {
	Token           string      `json:"token"`
	StytchSessionID string      `json:"stytch_session_id"`
	UserID          pgtype.UUID `json:"user_id"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	ExpiresAt       time.Time   `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Token,
		arg.StytchSessionID,
		arg.UserID,
		arg.TenantID,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.StytchSessionID,
		&i.UserID,
		&i.TenantID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT
    id,
    token,
    stytch_session_id,
    user_id,
    tenant_id,
    expires_at,
    created_at,
    last_seen_at
FROM sessions
WHERE token = $1
LIMIT 1
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.StytchSessionID,
		&i.UserID,
		&i.TenantID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const updateSessionLastSeen = `-- name: UpdateSessionLastSeen :exec
UPDATE sessions
SET last_seen_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateSessionLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateSessionLastSeen, id)
	return err
}
