// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: streams.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStream = `-- name: CreateStream :one
INSERT INTO streams (school_id, name, color)
VALUES ($1, $2, $3)
RETURNING id, school_id, name, color, created_at, updated_at
`

type CreateStreamParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Name     string      `json:"name"`
	Color    pgtype.Text `json:"color"`
}

func (q *Queries) CreateStream(ctx context.Context, arg CreateStreamParams) (Stream, error) {
	row := q.db.QueryRow(ctx, createStream, arg.SchoolID, arg.Name, arg.Color)
	var i Stream
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
