// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: streams.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStream = `-- name: CreateStream :one
INSERT INTO streams (school_id, name, color)
VALUES ($1, $2, $3)
RETURNING id, school_id, name, color, created_at, updated_at
`

type CreateStreamParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Name     string      `json:"name"`
	Color    pgtype.Text `json:"color"`
}

func (q *Queries) CreateStream(ctx context.Context, arg CreateStreamParams) (Stream, error) {
	row := q.db.QueryRow(ctx, createStream, arg.SchoolID, arg.Name, arg.Color)
	var i Stream
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStream = `-- name: GetStream :one
SELECT id, school_id, name, color FROM streams WHERE id = $1
`

type GetStreamRow struct {
	ID       pgtype.UUID `json:"id"`
	SchoolID pgtype.UUID `json:"school_id"`
	Name     string      `json:"name"`
	Color    pgtype.Text `json:"color"`
}

func (q *Queries) GetStream(ctx context.Context, id pgtype.UUID) (GetStreamRow, error) {
	row := q.db.QueryRow(ctx, getStream, id)
	var i GetStreamRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.Color,
	)
	return i, err
}

const listStreamsBySchool = `-- name: ListStreamsBySchool :many
SELECT id, school_id, name, color, created_at, updated_at FROM streams WHERE school_id = $1
`

func (q *Queries) ListStreamsBySchool(ctx context.Context, schoolID pgtype.UUID) ([]Stream, error) {
	rows, err := q.db.Query(ctx, listStreamsBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stream
	for rows.Next() {
		var i Stream
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
