// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: student_enrollments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEnrollments = `-- name: CountEnrollments :one
SELECT COUNT(*) FROM student_class_enrollments
WHERE school_id = $1
  AND ($2::uuid IS NULL OR class_room_id = $2)
  AND ($3::uuid IS NULL OR student_id = $3)
  AND ($4::text IS NULL OR $4 = '' OR status::text = $4)
`

type CountEnrollmentsParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Column2  pgtype.UUID `json:"column_2"`
	Column3  pgtype.UUID `json:"column_3"`
	Column4  string      `json:"column_4"`
}

func (q *Queries) CountEnrollments(ctx context.Context, arg CountEnrollmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEnrollments,
		arg.SchoolID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnassignedStudents = `-- name: CountUnassignedStudents :one
SELECT COUNT(*)
FROM students s
WHERE s.school_id = $1
  AND NOT EXISTS (
    SELECT 1 FROM student_class_enrollments sce
    WHERE sce.student_id = s.student_id
      AND sce.academic_year_id = $2
      AND sce.status = 'ACTIVE'
  )
`

type CountUnassignedStudentsParams struct {
	SchoolID       pgtype.UUID `json:"school_id"`
	AcademicYearID pgtype.UUID `json:"academic_year_id"`
}

func (q *Queries) CountUnassignedStudents(ctx context.Context, arg CountUnassignedStudentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnassignedStudents, arg.SchoolID, arg.AcademicYearID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO student_class_enrollments (
    school_id, student_id, class_room_id, academic_year_id, academic_term_id,
    status, enrolled_at, metadata
) VALUES ($1, $2, $3, $4, $5, 'ACTIVE', $6, $7)
RETURNING id, school_id, student_id, class_room_id, academic_year_id, academic_term_id, status, enrolled_at, completed_at, metadata, created_at, updated_at
`

type CreateEnrollmentParams struct {
	SchoolID       pgtype.UUID        `json:"school_id"`
	StudentID      pgtype.UUID        `json:"student_id"`
	ClassRoomID    pgtype.UUID        `json:"class_room_id"`
	AcademicYearID pgtype.UUID        `json:"academic_year_id"`
	AcademicTermID pgtype.UUID        `json:"academic_term_id"`
	EnrolledAt     pgtype.Timestamptz `json:"enrolled_at"`
	Metadata       []byte             `json:"metadata"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (StudentClassEnrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment,
		arg.SchoolID,
		arg.StudentID,
		arg.ClassRoomID,
		arg.AcademicYearID,
		arg.AcademicTermID,
		arg.EnrolledAt,
		arg.Metadata,
	)
	var i StudentClassEnrollment
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.StudentID,
		&i.ClassRoomID,
		&i.AcademicYearID,
		&i.AcademicTermID,
		&i.Status,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnrollment = `-- name: DeleteEnrollment :exec
DELETE FROM student_class_enrollments WHERE id = $1
`

func (q *Queries) DeleteEnrollment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnrollment, id)
	return err
}

const getActiveEnrollmentByStudent = `-- name: GetActiveEnrollmentByStudent :one
SELECT id, school_id, student_id, class_room_id, academic_year_id, academic_term_id, status, enrolled_at, completed_at, metadata, created_at, updated_at FROM student_class_enrollments
WHERE student_id = $1 AND academic_year_id = $2 AND status = 'ACTIVE'
`

type GetActiveEnrollmentByStudentParams struct {
	StudentID      pgtype.UUID `json:"student_id"`
	AcademicYearID pgtype.UUID `json:"academic_year_id"`
}

func (q *Queries) GetActiveEnrollmentByStudent(ctx context.Context, arg GetActiveEnrollmentByStudentParams) (StudentClassEnrollment, error) {
	row := q.db.QueryRow(ctx, getActiveEnrollmentByStudent, arg.StudentID, arg.AcademicYearID)
	var i StudentClassEnrollment
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.StudentID,
		&i.ClassRoomID,
		&i.AcademicYearID,
		&i.AcademicTermID,
		&i.Status,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassRoom = `-- name: GetClassRoom :one
SELECT id, academic_year_id, school_id FROM class_rooms WHERE id = $1
`

type GetClassRoomRow struct {
	ID             pgtype.UUID `json:"id"`
	AcademicYearID pgtype.UUID `json:"academic_year_id"`
	SchoolID       pgtype.UUID `json:"school_id"`
}

func (q *Queries) GetClassRoom(ctx context.Context, id pgtype.UUID) (GetClassRoomRow, error) {
	row := q.db.QueryRow(ctx, getClassRoom, id)
	var i GetClassRoomRow
	err := row.Scan(&i.ID, &i.AcademicYearID, &i.SchoolID)
	return i, err
}

const listEnrollments = `-- name: ListEnrollments :many
SELECT sce.id, sce.school_id, sce.student_id, sce.class_room_id, sce.academic_year_id, sce.academic_term_id, sce.status, sce.enrolled_at, sce.completed_at, sce.metadata, sce.created_at, sce.updated_at,
    cr.name as class_name, cr.grade_level_id, gl.local_label as grade,
    cr.stream, s.admission_number, s.full_name as student_name
FROM student_class_enrollments sce
JOIN class_rooms cr ON cr.id = sce.class_room_id
JOIN grade_levels gl ON gl.id = cr.grade_level_id
JOIN students s ON s.student_id = sce.student_id
WHERE sce.school_id = $1
  AND ($2::uuid IS NULL OR sce.class_room_id = $2)
  AND ($3::uuid IS NULL OR sce.student_id = $3)
  AND ($4::text IS NULL OR $4 = '' OR sce.status::text = $4)
ORDER BY sce.enrolled_at DESC
LIMIT $5 OFFSET $6
`

type ListEnrollmentsParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Column2  pgtype.UUID `json:"column_2"`
	Column3  pgtype.UUID `json:"column_3"`
	Column4  string      `json:"column_4"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListEnrollmentsRow struct {
	ID              pgtype.UUID        `json:"id"`
	SchoolID        pgtype.UUID        `json:"school_id"`
	StudentID       pgtype.UUID        `json:"student_id"`
	ClassRoomID     pgtype.UUID        `json:"class_room_id"`
	AcademicYearID  pgtype.UUID        `json:"academic_year_id"`
	AcademicTermID  pgtype.UUID        `json:"academic_term_id"`
	Status          EnrollmentStatus   `json:"status"`
	EnrolledAt      pgtype.Timestamptz `json:"enrolled_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ClassName       string             `json:"class_name"`
	GradeLevelID    pgtype.UUID        `json:"grade_level_id"`
	Grade           string             `json:"grade"`
	Stream          pgtype.Text        `json:"stream"`
	AdmissionNumber string             `json:"admission_number"`
	StudentName     string             `json:"student_name"`
}

func (q *Queries) ListEnrollments(ctx context.Context, arg ListEnrollmentsParams) ([]ListEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listEnrollments,
		arg.SchoolID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrollmentsRow
	for rows.Next() {
		var i ListEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.StudentID,
			&i.ClassRoomID,
			&i.AcademicYearID,
			&i.AcademicTermID,
			&i.Status,
			&i.EnrolledAt,
			&i.CompletedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClassName,
			&i.GradeLevelID,
			&i.Grade,
			&i.Stream,
			&i.AdmissionNumber,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignedStudents = `-- name: ListUnassignedStudents :many
SELECT s.student_id, s.full_name, s.admission_number
FROM students s
WHERE s.school_id = $1
  AND NOT EXISTS (
    SELECT 1 FROM student_class_enrollments sce
    WHERE sce.student_id = s.student_id
      AND sce.academic_year_id = $2
      AND sce.status = 'ACTIVE'
  )
ORDER BY s.full_name
LIMIT $3 OFFSET $4
`

type ListUnassignedStudentsParams struct {
	SchoolID       pgtype.UUID `json:"school_id"`
	AcademicYearID pgtype.UUID `json:"academic_year_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

type ListUnassignedStudentsRow struct {
	StudentID       pgtype.UUID `json:"student_id"`
	FullName        string      `json:"full_name"`
	AdmissionNumber string      `json:"admission_number"`
}

func (q *Queries) ListUnassignedStudents(ctx context.Context, arg ListUnassignedStudentsParams) ([]ListUnassignedStudentsRow, error) {
	rows, err := q.db.Query(ctx, listUnassignedStudents,
		arg.SchoolID,
		arg.AcademicYearID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnassignedStudentsRow
	for rows.Next() {
		var i ListUnassignedStudentsRow
		if err := rows.Scan(&i.StudentID, &i.FullName, &i.AdmissionNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnrollment = `-- name: UpdateEnrollment :one
UPDATE student_class_enrollments
SET class_room_id = COALESCE($2, class_room_id),
    status = COALESCE($3, status),
    metadata = COALESCE($4, metadata),
    updated_at = NOW()
WHERE id = $1
RETURNING id, school_id, student_id, class_room_id, academic_year_id, academic_term_id, status, enrolled_at, completed_at, metadata, created_at, updated_at
`

type UpdateEnrollmentParams struct {
	ID          pgtype.UUID      `json:"id"`
	ClassRoomID pgtype.UUID      `json:"class_room_id"`
	Status      EnrollmentStatus `json:"status"`
	Metadata    []byte           `json:"metadata"`
}

func (q *Queries) UpdateEnrollment(ctx context.Context, arg UpdateEnrollmentParams) (StudentClassEnrollment, error) {
	row := q.db.QueryRow(ctx, updateEnrollment,
		arg.ID,
		arg.ClassRoomID,
		arg.Status,
		arg.Metadata,
	)
	var i StudentClassEnrollment
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.StudentID,
		&i.ClassRoomID,
		&i.AcademicYearID,
		&i.AcademicTermID,
		&i.Status,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
