// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStudents = `-- name: CountStudents :one
SELECT COUNT(*)
FROM students
WHERE school_id = $1
  AND (
    $2::text = '' OR
    full_name ILIKE '%' || $2 || '%' OR
    admission_number ILIKE '%' || $2 || '%'
  )
`

type CountStudentsParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Column2  string      `json:"column_2"`
}

func (q *Queries) CountStudents(ctx context.Context, arg CountStudentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudents, arg.SchoolID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listStudents = `-- name: ListStudents :many
SELECT
    student_id,
    school_id,
    admission_number,
    full_name,
    date_of_birth,
    gender,
    metadata,
    created_at,
    updated_at
FROM students
WHERE school_id = $1
  AND (
    $2::text = '' OR
    full_name ILIKE '%' || $2 || '%' OR
    admission_number ILIKE '%' || $2 || '%'
  )
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListStudentsParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Column2  string      `json:"column_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListStudents(ctx context.Context, arg ListStudentsParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudents,
		arg.SchoolID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.StudentID,
			&i.SchoolID,
			&i.AdmissionNumber,
			&i.FullName,
			&i.DateOfBirth,
			&i.Gender,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
