// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStudents = `-- name: CountStudents :one
SELECT COUNT(*)
FROM students s
LEFT JOIN LATERAL (
    SELECT sce.class_room_id
    FROM student_class_enrollments sce
    WHERE sce.student_id = s.student_id
      AND sce.status = 'ACTIVE'
    ORDER BY sce.enrolled_at DESC
    LIMIT 1
) e ON true
LEFT JOIN class_rooms c ON c.id = e.class_room_id
WHERE s.school_id = $1
  AND (
    $2::text = '' OR
    s.full_name ILIKE '%' || $2 || '%' OR
    s.admission_number ILIKE '%' || $2 || '%'
  )
  AND ($3::uuid IS NULL OR c.id = $3)
`

type CountStudentsParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Column2  string      `json:"column_2"`
	Column3  pgtype.UUID `json:"column_3"`
}

func (q *Queries) CountStudents(ctx context.Context, arg CountStudentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudents, arg.SchoolID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listStudents = `-- name: ListStudents :many
SELECT
    s.student_id,
    s.school_id,
    s.admission_number,
    s.full_name,
    s.date_of_birth,
    s.gender,
    s.metadata,
    s.created_at,
    s.updated_at,
    c.id AS class_id,
    c.name AS class_name
FROM students s
LEFT JOIN LATERAL (
    SELECT sce.class_room_id
    FROM student_class_enrollments sce
    WHERE sce.student_id = s.student_id
      AND sce.status = 'ACTIVE'
    ORDER BY sce.enrolled_at DESC
    LIMIT 1
) e ON true
LEFT JOIN class_rooms c ON c.id = e.class_room_id
WHERE s.school_id = $1
  AND (
    $2::text = '' OR
    s.full_name ILIKE '%' || $2 || '%' OR
    s.admission_number ILIKE '%' || $2 || '%'
  )
  AND ($5::uuid IS NULL OR c.id = $5)
ORDER BY s.created_at DESC
LIMIT $3 OFFSET $4
`

type ListStudentsParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Column2  string      `json:"column_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Column5  pgtype.UUID `json:"column_5"`
}

type ListStudentsRow struct {
	StudentID       pgtype.UUID        `json:"student_id"`
	SchoolID        pgtype.UUID        `json:"school_id"`
	AdmissionNumber string             `json:"admission_number"`
	FullName        string             `json:"full_name"`
	DateOfBirth     pgtype.Date        `json:"date_of_birth"`
	Gender          interface{}        `json:"gender"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ClassID         pgtype.UUID        `json:"class_id"`
	ClassName       pgtype.Text        `json:"class_name"`
}

func (q *Queries) ListStudents(ctx context.Context, arg ListStudentsParams) ([]ListStudentsRow, error) {
	rows, err := q.db.Query(ctx, listStudents,
		arg.SchoolID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentsRow
	for rows.Next() {
		var i ListStudentsRow
		if err := rows.Scan(
			&i.StudentID,
			&i.SchoolID,
			&i.AdmissionNumber,
			&i.FullName,
			&i.DateOfBirth,
			&i.Gender,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClassID,
			&i.ClassName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
