// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sub_topics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSubTopicsByTopic = `-- name: CountSubTopicsByTopic :one
SELECT COUNT(*) FROM sub_topics WHERE topic_id = $1
`

func (q *Queries) CountSubTopicsByTopic(ctx context.Context, topicID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSubTopicsByTopic, topicID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSubTopicByID = `-- name: GetSubTopicByID :one
SELECT id, topic_id, name, sequence_index FROM sub_topics WHERE id = $1
`

type GetSubTopicByIDRow struct {
	ID            pgtype.UUID `json:"id"`
	TopicID       pgtype.UUID `json:"topic_id"`
	Name          string      `json:"name"`
	SequenceIndex int32       `json:"sequence_index"`
}

func (q *Queries) GetSubTopicByID(ctx context.Context, id pgtype.UUID) (GetSubTopicByIDRow, error) {
	row := q.db.QueryRow(ctx, getSubTopicByID, id)
	var i GetSubTopicByIDRow
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.Name,
		&i.SequenceIndex,
	)
	return i, err
}

const listSubTopics = `-- name: ListSubTopics :many
SELECT id, topic_id, name, sequence_index FROM sub_topics ORDER BY topic_id, sequence_index ASC LIMIT $1 OFFSET $2
`

type ListSubTopicsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSubTopicsRow struct {
	ID            pgtype.UUID `json:"id"`
	TopicID       pgtype.UUID `json:"topic_id"`
	Name          string      `json:"name"`
	SequenceIndex int32       `json:"sequence_index"`
}

func (q *Queries) ListSubTopics(ctx context.Context, arg ListSubTopicsParams) ([]ListSubTopicsRow, error) {
	rows, err := q.db.Query(ctx, listSubTopics, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubTopicsRow
	for rows.Next() {
		var i ListSubTopicsRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Name,
			&i.SequenceIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubTopicsByTopic = `-- name: ListSubTopicsByTopic :many
SELECT id, topic_id, name, sequence_index FROM sub_topics WHERE topic_id = $1 ORDER BY sequence_index ASC
`

type ListSubTopicsByTopicRow struct {
	ID            pgtype.UUID `json:"id"`
	TopicID       pgtype.UUID `json:"topic_id"`
	Name          string      `json:"name"`
	SequenceIndex int32       `json:"sequence_index"`
}

func (q *Queries) ListSubTopicsByTopic(ctx context.Context, topicID pgtype.UUID) ([]ListSubTopicsByTopicRow, error) {
	rows, err := q.db.Query(ctx, listSubTopicsByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubTopicsByTopicRow
	for rows.Next() {
		var i ListSubTopicsByTopicRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Name,
			&i.SequenceIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
