// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subjects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSearchSubjects = `-- name: CountSearchSubjects :one
SELECT COUNT(*) FROM subjects s LEFT JOIN grade_levels gl ON gl.id = s.grade_level_id WHERE (s.name ILIKE $1 OR s.code ILIKE $1)
`

func (q *Queries) CountSearchSubjects(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchSubjects, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubjects = `-- name: CountSubjects :one
SELECT COUNT(*) FROM subjects s LEFT JOIN grade_levels gl ON gl.id = s.grade_level_id
`

func (q *Queries) CountSubjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSubjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSubjectByID = `-- name: GetSubjectByID :one
SELECT id, education_system_id, name, code, type, grade_level_id, color, created_at, updated_at FROM subjects WHERE id = $1
`

type GetSubjectByIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	EducationSystemID pgtype.UUID        `json:"education_system_id"`
	Name              string             `json:"name"`
	Code              string             `json:"code"`
	Type              string             `json:"type"`
	GradeLevelID      pgtype.UUID        `json:"grade_level_id"`
	Color             pgtype.Text        `json:"color"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSubjectByID(ctx context.Context, id pgtype.UUID) (GetSubjectByIDRow, error) {
	row := q.db.QueryRow(ctx, getSubjectByID, id)
	var i GetSubjectByIDRow
	err := row.Scan(
		&i.ID,
		&i.EducationSystemID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.GradeLevelID,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT s.id, s.grade_level_id, s.name, s.code, COALESCE(s.color, ''), COALESCE(gl.local_label, '') FROM subjects s LEFT JOIN grade_levels gl ON gl.id = s.grade_level_id ORDER BY s.name ASC LIMIT $1 OFFSET $2
`

type ListSubjectsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSubjectsRow struct {
	ID           pgtype.UUID `json:"id"`
	GradeLevelID pgtype.UUID `json:"grade_level_id"`
	Name         string      `json:"name"`
	Code         string      `json:"code"`
	Color        string      `json:"color"`
	LocalLabel   string      `json:"local_label"`
}

func (q *Queries) ListSubjects(ctx context.Context, arg ListSubjectsParams) ([]ListSubjectsRow, error) {
	rows, err := q.db.Query(ctx, listSubjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubjectsRow
	for rows.Next() {
		var i ListSubjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.GradeLevelID,
			&i.Name,
			&i.Code,
			&i.Color,
			&i.LocalLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjectsBySystem = `-- name: ListSubjectsBySystem :many
SELECT id, education_system_id, name, code, type, grade_level_id, color, created_at, updated_at FROM subjects WHERE education_system_id = $1 ORDER BY name ASC
`

type ListSubjectsBySystemRow struct {
	ID                pgtype.UUID        `json:"id"`
	EducationSystemID pgtype.UUID        `json:"education_system_id"`
	Name              string             `json:"name"`
	Code              string             `json:"code"`
	Type              string             `json:"type"`
	GradeLevelID      pgtype.UUID        `json:"grade_level_id"`
	Color             pgtype.Text        `json:"color"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSubjectsBySystem(ctx context.Context, educationSystemID pgtype.UUID) ([]ListSubjectsBySystemRow, error) {
	rows, err := q.db.Query(ctx, listSubjectsBySystem, educationSystemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubjectsBySystemRow
	for rows.Next() {
		var i ListSubjectsBySystemRow
		if err := rows.Scan(
			&i.ID,
			&i.EducationSystemID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.GradeLevelID,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSubjects = `-- name: SearchSubjects :many
SELECT s.id, s.grade_level_id, s.name, s.code, COALESCE(s.color, ''), COALESCE(gl.local_label, '') FROM subjects s LEFT JOIN grade_levels gl ON gl.id = s.grade_level_id WHERE (s.name ILIKE $1 OR s.code ILIKE $1) ORDER BY s.name ASC LIMIT $2 OFFSET $3
`

type SearchSubjectsParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type SearchSubjectsRow struct {
	ID           pgtype.UUID `json:"id"`
	GradeLevelID pgtype.UUID `json:"grade_level_id"`
	Name         string      `json:"name"`
	Code         string      `json:"code"`
	Color        string      `json:"color"`
	LocalLabel   string      `json:"local_label"`
}

func (q *Queries) SearchSubjects(ctx context.Context, arg SearchSubjectsParams) ([]SearchSubjectsRow, error) {
	rows, err := q.db.Query(ctx, searchSubjects, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSubjectsRow
	for rows.Next() {
		var i SearchSubjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.GradeLevelID,
			&i.Name,
			&i.Code,
			&i.Color,
			&i.LocalLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
