// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teachers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTeacherSummary = `-- name: GetTeacherSummary :one
SELECT
  COUNT(*) AS total_teachers,
  COUNT(*) FILTER (WHERE NOT EXISTS (
    SELECT 1
    FROM class_timetable_slots cts
    WHERE cts.teacher_membership_id = sm.id
      AND cts.academic_term_id = $2
  )) AS teachers_without_assignment
FROM school_memberships sm
WHERE sm.school_id = $1
  AND sm.role = 'TEACHER'
  AND sm.is_active = true
`

type GetTeacherSummaryParams struct {
	SchoolID       pgtype.UUID `json:"school_id"`
	AcademicTermID pgtype.UUID `json:"academic_term_id"`
}

type GetTeacherSummaryRow struct {
	TotalTeachers             int64 `json:"total_teachers"`
	TeachersWithoutAssignment int64 `json:"teachers_without_assignment"`
}

func (q *Queries) GetTeacherSummary(ctx context.Context, arg GetTeacherSummaryParams) (GetTeacherSummaryRow, error) {
	row := q.db.QueryRow(ctx, getTeacherSummary, arg.SchoolID, arg.AcademicTermID)
	var i GetTeacherSummaryRow
	err := row.Scan(&i.TotalTeachers, &i.TeachersWithoutAssignment)
	return i, err
}
