// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlc

import (
	"context"
)

const getTenantByStytchOrgID = `-- name: GetTenantByStytchOrgID :one
SELECT
    id,
    name,
    slug,
    stytch_org_id,
    created_at
FROM tenants
WHERE stytch_org_id = $1
LIMIT 1
`

func (q *Queries) GetTenantByStytchOrgID(ctx context.Context, stytchOrgID string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByStytchOrgID, stytchOrgID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.StytchOrgID,
		&i.CreatedAt,
	)
	return i, err
}
