// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timetable_substitutions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSubstitutionConflicts = `-- name: CountSubstitutionConflicts :one
SELECT COUNT(*) FROM timetable_substitutions
WHERE school_id = $1
  AND class_timetable_slot_id = $2
  AND substitution_date = $3
  AND substitute_teacher_membership_id = $4
  AND status IN ('PENDING', 'ASSIGNED')
  AND ($5::uuid IS NULL OR id != $5)
`

type CountSubstitutionConflictsParams struct {
	SchoolID                      pgtype.UUID `json:"school_id"`
	ClassTimetableSlotID          pgtype.UUID `json:"class_timetable_slot_id"`
	SubstitutionDate              pgtype.Date `json:"substitution_date"`
	SubstituteTeacherMembershipID pgtype.UUID `json:"substitute_teacher_membership_id"`
	Column5                       pgtype.UUID `json:"column_5"`
}

func (q *Queries) CountSubstitutionConflicts(ctx context.Context, arg CountSubstitutionConflictsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubstitutionConflicts,
		arg.SchoolID,
		arg.ClassTimetableSlotID,
		arg.SubstitutionDate,
		arg.SubstituteTeacherMembershipID,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTimetableSubstitutions = `-- name: CountTimetableSubstitutions :one
SELECT COUNT(*) FROM timetable_substitutions ts
WHERE ts.school_id = $1
  AND ($2::date IS NULL OR ts.substitution_date >= $2)
  AND ($3::date IS NULL OR ts.substitution_date <= $3)
  AND ($4::text IS NULL OR ts.status = $4)
`

type CountTimetableSubstitutionsParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Column2  pgtype.Date `json:"column_2"`
	Column3  pgtype.Date `json:"column_3"`
	Column4  string      `json:"column_4"`
}

func (q *Queries) CountTimetableSubstitutions(ctx context.Context, arg CountTimetableSubstitutionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTimetableSubstitutions,
		arg.SchoolID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTimetableSubstitution = `-- name: CreateTimetableSubstitution :one
INSERT INTO timetable_substitutions (school_id, class_timetable_slot_id, substitution_date, original_teacher_membership_id, substitute_teacher_membership_id, status, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, school_id, class_timetable_slot_id, substitution_date, original_teacher_membership_id, substitute_teacher_membership_id, status, reason, created_at, updated_at
`

type CreateTimetableSubstitutionParams struct {
	SchoolID                      pgtype.UUID        `json:"school_id"`
	ClassTimetableSlotID          pgtype.UUID        `json:"class_timetable_slot_id"`
	SubstitutionDate              pgtype.Date        `json:"substitution_date"`
	OriginalTeacherMembershipID   pgtype.UUID        `json:"original_teacher_membership_id"`
	SubstituteTeacherMembershipID pgtype.UUID        `json:"substitute_teacher_membership_id"`
	Status                        SubstitutionStatus `json:"status"`
	Reason                        pgtype.Text        `json:"reason"`
}

func (q *Queries) CreateTimetableSubstitution(ctx context.Context, arg CreateTimetableSubstitutionParams) (TimetableSubstitution, error) {
	row := q.db.QueryRow(ctx, createTimetableSubstitution,
		arg.SchoolID,
		arg.ClassTimetableSlotID,
		arg.SubstitutionDate,
		arg.OriginalTeacherMembershipID,
		arg.SubstituteTeacherMembershipID,
		arg.Status,
		arg.Reason,
	)
	var i TimetableSubstitution
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.ClassTimetableSlotID,
		&i.SubstitutionDate,
		&i.OriginalTeacherMembershipID,
		&i.SubstituteTeacherMembershipID,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTimetableSubstitution = `-- name: DeleteTimetableSubstitution :exec
DELETE FROM timetable_substitutions WHERE id = $1
`

func (q *Queries) DeleteTimetableSubstitution(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTimetableSubstitution, id)
	return err
}

const getTimetableSubstitution = `-- name: GetTimetableSubstitution :one
SELECT id, school_id, class_timetable_slot_id, substitution_date, original_teacher_membership_id, substitute_teacher_membership_id, status, reason, created_at, updated_at
FROM timetable_substitutions
WHERE id = $1 AND school_id = $2
`

type GetTimetableSubstitutionParams struct {
	ID       pgtype.UUID `json:"id"`
	SchoolID pgtype.UUID `json:"school_id"`
}

func (q *Queries) GetTimetableSubstitution(ctx context.Context, arg GetTimetableSubstitutionParams) (TimetableSubstitution, error) {
	row := q.db.QueryRow(ctx, getTimetableSubstitution, arg.ID, arg.SchoolID)
	var i TimetableSubstitution
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.ClassTimetableSlotID,
		&i.SubstitutionDate,
		&i.OriginalTeacherMembershipID,
		&i.SubstituteTeacherMembershipID,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTimetableSubstitutions = `-- name: ListTimetableSubstitutions :many
SELECT ts.id, ts.school_id, ts.class_timetable_slot_id, ts.substitution_date, ts.original_teacher_membership_id, ts.substitute_teacher_membership_id, ts.status, ts.reason, ts.created_at, ts.updated_at,
    cts.class_room_id, cr.name as class_name,
    s.name as subject_name,
    tm.user_id as original_teacher_id, u.full_name as original_teacher_name,
    stm.user_id as substitute_teacher_id, su.full_name as substitute_teacher_name,
    tsl.name as time_slot_name, tsl.start_time, tsl.end_time
FROM timetable_substitutions ts
JOIN class_timetable_slots cts ON cts.id = ts.class_timetable_slot_id
JOIN class_rooms cr ON cr.id = cts.class_room_id
JOIN subjects s ON s.id = cts.subject_id
JOIN school_memberships tm ON tm.id = cts.teacher_membership_id
JOIN users u ON u.id = tm.user_id
LEFT JOIN school_memberships stm ON stm.id = ts.substitute_teacher_membership_id
LEFT JOIN users su ON su.id = stm.user_id
JOIN time_slots tsl ON tsl.id = cts.time_slot_id
WHERE ts.school_id = $1
  AND ($2::date IS NULL OR ts.substitution_date >= $2)
  AND ($3::date IS NULL OR ts.substitution_date <= $3)
  AND ($4::text IS NULL OR ts.status = $4)
ORDER BY ts.substitution_date, tsl.start_time
LIMIT $5 OFFSET $6
`

type ListTimetableSubstitutionsParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Column2  pgtype.Date `json:"column_2"`
	Column3  pgtype.Date `json:"column_3"`
	Column4  string      `json:"column_4"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListTimetableSubstitutionsRow struct {
	ID                            pgtype.UUID        `json:"id"`
	SchoolID                      pgtype.UUID        `json:"school_id"`
	ClassTimetableSlotID          pgtype.UUID        `json:"class_timetable_slot_id"`
	SubstitutionDate              pgtype.Date        `json:"substitution_date"`
	OriginalTeacherMembershipID   pgtype.UUID        `json:"original_teacher_membership_id"`
	SubstituteTeacherMembershipID pgtype.UUID        `json:"substitute_teacher_membership_id"`
	Status                        SubstitutionStatus `json:"status"`
	Reason                        pgtype.Text        `json:"reason"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	ClassRoomID                   pgtype.UUID        `json:"class_room_id"`
	ClassName                     string             `json:"class_name"`
	SubjectName                   string             `json:"subject_name"`
	OriginalTeacherID             pgtype.UUID        `json:"original_teacher_id"`
	OriginalTeacherName           string             `json:"original_teacher_name"`
	SubstituteTeacherID           pgtype.UUID        `json:"substitute_teacher_id"`
	SubstituteTeacherName         pgtype.Text        `json:"substitute_teacher_name"`
	TimeSlotName                  string             `json:"time_slot_name"`
	StartTime                     pgtype.Time        `json:"start_time"`
	EndTime                       pgtype.Time        `json:"end_time"`
}

func (q *Queries) ListTimetableSubstitutions(ctx context.Context, arg ListTimetableSubstitutionsParams) ([]ListTimetableSubstitutionsRow, error) {
	rows, err := q.db.Query(ctx, listTimetableSubstitutions,
		arg.SchoolID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimetableSubstitutionsRow
	for rows.Next() {
		var i ListTimetableSubstitutionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.ClassTimetableSlotID,
			&i.SubstitutionDate,
			&i.OriginalTeacherMembershipID,
			&i.SubstituteTeacherMembershipID,
			&i.Status,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClassRoomID,
			&i.ClassName,
			&i.SubjectName,
			&i.OriginalTeacherID,
			&i.OriginalTeacherName,
			&i.SubstituteTeacherID,
			&i.SubstituteTeacherName,
			&i.TimeSlotName,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimetableSubstitution = `-- name: UpdateTimetableSubstitution :exec
UPDATE timetable_substitutions
SET substitute_teacher_membership_id = COALESCE($3, substitute_teacher_membership_id),
    status = COALESCE($4, status),
    reason = COALESCE($5, reason),
    updated_at = NOW()
WHERE id = $1 AND school_id = $2
`

type UpdateTimetableSubstitutionParams struct {
	ID                            pgtype.UUID        `json:"id"`
	SchoolID                      pgtype.UUID        `json:"school_id"`
	SubstituteTeacherMembershipID pgtype.UUID        `json:"substitute_teacher_membership_id"`
	Status                        SubstitutionStatus `json:"status"`
	Reason                        pgtype.Text        `json:"reason"`
}

func (q *Queries) UpdateTimetableSubstitution(ctx context.Context, arg UpdateTimetableSubstitutionParams) error {
	_, err := q.db.Exec(ctx, updateTimetableSubstitution,
		arg.ID,
		arg.SchoolID,
		arg.SubstituteTeacherMembershipID,
		arg.Status,
		arg.Reason,
	)
	return err
}
