// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timetable_templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTimetableTemplate = `-- name: CreateTimetableTemplate :one
INSERT INTO timetable_templates (id, school_id, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateTimetableTemplateParams struct {
	ID          pgtype.UUID `json:"id"`
	SchoolID    pgtype.UUID `json:"school_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateTimetableTemplate(ctx context.Context, arg CreateTimetableTemplateParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTimetableTemplate,
		arg.ID,
		arg.SchoolID,
		arg.Name,
		arg.Description,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getTimetableTemplate = `-- name: GetTimetableTemplate :one
SELECT id, school_id, name, description, created_at, updated_at
FROM timetable_templates
WHERE id = $1
`

func (q *Queries) GetTimetableTemplate(ctx context.Context, id pgtype.UUID) (TimetableTemplate, error) {
	row := q.db.QueryRow(ctx, getTimetableTemplate, id)
	var i TimetableTemplate
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTimetableTemplatesBySchool = `-- name: ListTimetableTemplatesBySchool :many
SELECT id, school_id, name, description, created_at, updated_at
FROM timetable_templates
WHERE school_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTimetableTemplatesBySchool(ctx context.Context, schoolID pgtype.UUID) ([]TimetableTemplate, error) {
	rows, err := q.db.Query(ctx, listTimetableTemplatesBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimetableTemplate
	for rows.Next() {
		var i TimetableTemplate
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimetableTemplate = `-- name: UpdateTimetableTemplate :exec
UPDATE timetable_templates
SET name = $2, description = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateTimetableTemplateParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateTimetableTemplate(ctx context.Context, arg UpdateTimetableTemplateParams) error {
	_, err := q.db.Exec(ctx, updateTimetableTemplate, arg.ID, arg.Name, arg.Description)
	return err
}
