// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: time_slots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTimeSlot = `-- name: CreateTimeSlot :one
INSERT INTO time_slots (id, school_id, timetable_template_id, name, start_time, end_time, sequence_index, is_instructional)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateTimeSlotParams struct {
	ID                  pgtype.UUID `json:"id"`
	SchoolID            pgtype.UUID `json:"school_id"`
	TimetableTemplateID pgtype.UUID `json:"timetable_template_id"`
	Name                string      `json:"name"`
	StartTime           pgtype.Time `json:"start_time"`
	EndTime             pgtype.Time `json:"end_time"`
	SequenceIndex       int32       `json:"sequence_index"`
	IsInstructional     bool        `json:"is_instructional"`
}

func (q *Queries) CreateTimeSlot(ctx context.Context, arg CreateTimeSlotParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTimeSlot,
		arg.ID,
		arg.SchoolID,
		arg.TimetableTemplateID,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.SequenceIndex,
		arg.IsInstructional,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listTimeSlotsByTemplate = `-- name: ListTimeSlotsByTemplate :many
SELECT id, school_id, timetable_template_id, name, start_time, end_time, sequence_index, is_instructional, created_at, updated_at
FROM time_slots
WHERE timetable_template_id = $1
ORDER BY sequence_index ASC
`

func (q *Queries) ListTimeSlotsByTemplate(ctx context.Context, timetableTemplateID pgtype.UUID) ([]TimeSlot, error) {
	rows, err := q.db.Query(ctx, listTimeSlotsByTemplate, timetableTemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeSlot
	for rows.Next() {
		var i TimeSlot
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.TimetableTemplateID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.SequenceIndex,
			&i.IsInstructional,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
