// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timetable_substitutions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTimetableSubstitution = `-- name: CreateTimetableSubstitution :one
INSERT INTO timetable_substitutions (school_id, class_timetable_slot_id, substitution_date, original_teacher_membership_id, substitute_teacher_membership_id, status, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, school_id, class_timetable_slot_id, substitution_date, original_teacher_membership_id, substitute_teacher_membership_id, status, reason, created_at, updated_at
`

type CreateTimetableSubstitutionParams struct {
	SchoolID                      pgtype.UUID        `json:"school_id"`
	ClassTimetableSlotID          pgtype.UUID        `json:"class_timetable_slot_id"`
	SubstitutionDate              pgtype.Date        `json:"substitution_date"`
	OriginalTeacherMembershipID   pgtype.UUID        `json:"original_teacher_membership_id"`
	SubstituteTeacherMembershipID pgtype.UUID        `json:"substitute_teacher_membership_id"`
	Status                        SubstitutionStatus `json:"status"`
	Reason                        pgtype.Text        `json:"reason"`
}

func (q *Queries) CreateTimetableSubstitution(ctx context.Context, arg CreateTimetableSubstitutionParams) (TimetableSubstitution, error) {
	row := q.db.QueryRow(ctx, createTimetableSubstitution,
		arg.SchoolID,
		arg.ClassTimetableSlotID,
		arg.SubstitutionDate,
		arg.OriginalTeacherMembershipID,
		arg.SubstituteTeacherMembershipID,
		arg.Status,
		arg.Reason,
	)
	var i TimetableSubstitution
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.ClassTimetableSlotID,
		&i.SubstitutionDate,
		&i.OriginalTeacherMembershipID,
		&i.SubstituteTeacherMembershipID,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTimetableSubstitution = `-- name: DeleteTimetableSubstitution :exec
DELETE FROM timetable_substitutions WHERE id = $1
`

func (q *Queries) DeleteTimetableSubstitution(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTimetableSubstitution, id)
	return err
}

const getTimetableSubstitution = `-- name: GetTimetableSubstitution :one
SELECT id, school_id, class_timetable_slot_id, substitution_date, original_teacher_membership_id, substitute_teacher_membership_id, status, reason, created_at, updated_at
FROM timetable_substitutions
WHERE id = $1
`

func (q *Queries) GetTimetableSubstitution(ctx context.Context, id pgtype.UUID) (TimetableSubstitution, error) {
	row := q.db.QueryRow(ctx, getTimetableSubstitution, id)
	var i TimetableSubstitution
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.ClassTimetableSlotID,
		&i.SubstitutionDate,
		&i.OriginalTeacherMembershipID,
		&i.SubstituteTeacherMembershipID,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTimetableSubstitution = `-- name: UpdateTimetableSubstitution :exec
UPDATE timetable_substitutions
SET substitute_teacher_membership_id = COALESCE($3, substitute_teacher_membership_id),
    status = COALESCE($4, status),
    reason = COALESCE($5, reason),
    updated_at = NOW()
WHERE id = $1 AND school_id = $2
`

type UpdateTimetableSubstitutionParams struct {
	ID                            pgtype.UUID        `json:"id"`
	SchoolID                      pgtype.UUID        `json:"school_id"`
	SubstituteTeacherMembershipID pgtype.UUID        `json:"substitute_teacher_membership_id"`
	Status                        SubstitutionStatus `json:"status"`
	Reason                        pgtype.Text        `json:"reason"`
}

func (q *Queries) UpdateTimetableSubstitution(ctx context.Context, arg UpdateTimetableSubstitutionParams) error {
	_, err := q.db.Exec(ctx, updateTimetableSubstitution,
		arg.ID,
		arg.SchoolID,
		arg.SubstituteTeacherMembershipID,
		arg.Status,
		arg.Reason,
	)
	return err
}
