// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTopicsBySubject = `-- name: CountTopicsBySubject :one
SELECT COUNT(*) FROM topics WHERE subject_id = $1
`

func (q *Queries) CountTopicsBySubject(ctx context.Context, subjectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTopicsBySubject, subjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTopicByID = `-- name: GetTopicByID :one
SELECT id, subject_id, name, sequence_index FROM topics WHERE id = $1
`

type GetTopicByIDRow struct {
	ID            pgtype.UUID `json:"id"`
	SubjectID     pgtype.UUID `json:"subject_id"`
	Name          string      `json:"name"`
	SequenceIndex int32       `json:"sequence_index"`
}

func (q *Queries) GetTopicByID(ctx context.Context, id pgtype.UUID) (GetTopicByIDRow, error) {
	row := q.db.QueryRow(ctx, getTopicByID, id)
	var i GetTopicByIDRow
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Name,
		&i.SequenceIndex,
	)
	return i, err
}

const listTopics = `-- name: ListTopics :many
SELECT id, subject_id, name, sequence_index FROM topics ORDER BY subject_id, sequence_index ASC LIMIT $1 OFFSET $2
`

type ListTopicsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListTopicsRow struct {
	ID            pgtype.UUID `json:"id"`
	SubjectID     pgtype.UUID `json:"subject_id"`
	Name          string      `json:"name"`
	SequenceIndex int32       `json:"sequence_index"`
}

func (q *Queries) ListTopics(ctx context.Context, arg ListTopicsParams) ([]ListTopicsRow, error) {
	rows, err := q.db.Query(ctx, listTopics, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopicsRow
	for rows.Next() {
		var i ListTopicsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Name,
			&i.SequenceIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicsBySubject = `-- name: ListTopicsBySubject :many
SELECT id, subject_id, name, sequence_index FROM topics WHERE subject_id = $1 ORDER BY sequence_index ASC
`

type ListTopicsBySubjectRow struct {
	ID            pgtype.UUID `json:"id"`
	SubjectID     pgtype.UUID `json:"subject_id"`
	Name          string      `json:"name"`
	SequenceIndex int32       `json:"sequence_index"`
}

func (q *Queries) ListTopicsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]ListTopicsBySubjectRow, error) {
	rows, err := q.db.Query(ctx, listTopicsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopicsBySubjectRow
	for rows.Next() {
		var i ListTopicsBySubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Name,
			&i.SequenceIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
