// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    email,
    tenant_id,
    full_name,
    is_active,
    external_auth_id,
    created_at,
    updated_at
FROM users
WHERE email = $1
  AND tenant_id = $2
LIMIT 1
`

type GetUserByEmailParams struct {
	Email    string      `json:"email"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TenantID,
		&i.FullName,
		&i.IsActive,
		&i.ExternalAuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    email,
    tenant_id,
    full_name,
    is_active,
    external_auth_id,
    created_at,
    updated_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TenantID,
		&i.FullName,
		&i.IsActive,
		&i.ExternalAuthID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
